/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{sku}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_products__sku__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List */
        get: operations["admin_list_api_admin_products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_admin_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{sku}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Product
         * @description Retire a product.
         *
         *     The default is a soft delete: it disappears from the storefront but stays
         *     readable from the quotes that reference it. `hard=true` really removes the
         *     row, and is meant for mistakes rather than for discontinued stock.
         */
        delete: operations["delete_product_api_admin_products__sku__delete"];
        options?: never;
        head?: never;
        /** Update Product */
        patch: operations["update_product_api_admin_products__sku__patch"];
        trace?: never;
    };
    "/api/admin/products/{sku}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Product */
        post: operations["restore_product_api_admin_products__sku__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Quote
         * @description Accept a quote request.
         *
         *     Deliberately open: a customer should not need an account to ask for a price.
         *     If the email matches a registered user the quote is linked to them so it
         *     appears in their history, but that is a convenience, not a requirement.
         */
        post: operations["submit_quote_api_quotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Quotes
         * @description The signed-in user's own quote requests, newest first.
         *
         *     Matched on the email as well as the account id, so a request sent before
         *     the account existed still shows up once they register with that address.
         */
        get: operations["my_quotes_api_quotes_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Quotes */
        get: operations["list_quotes_api_admin_quotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/quotes/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quote */
        get: operations["get_quote_api_admin_quotes__reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Quote */
        patch: operations["update_quote_api_admin_quotes__reference__patch"];
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Used by the container healthcheck and by the frontend to show status.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ProductCreate */
        ProductCreate: {
            /** Sku */
            sku: string;
            /** Slug */
            slug: string;
            /** Kind */
            kind: string;
            /** Brand */
            brand: string;
            /** Model */
            model: string;
            /** Mpn */
            mpn?: string | null;
            /**
             * Family
             * @default
             */
            family: string;
            /**
             * Condition
             * @default new
             */
            condition: string;
            /**
             * Segment
             * @default datacenter
             */
            segment: string;
            /**
             * Price Pkr
             * @default 0
             */
            price_pkr: number;
            /**
             * Price On Request
             * @default false
             */
            price_on_request: boolean;
            /**
             * Stock Qty
             * @default 0
             */
            stock_qty: number;
            /**
             * Lead Days
             * @default 0
             */
            lead_days: number;
            /**
             * Indent Only
             * @default false
             */
            indent_only: boolean;
            /**
             * Warranty Months
             * @default 12
             */
            warranty_months: number;
            /**
             * Release Year
             * @default 2024
             */
            release_year: number;
            /**
             * Search Key
             * @default
             */
            search_key: string;
            /** Highlights */
            highlights?: string[];
            /** Tags */
            tags?: string[];
            /** Specs */
            specs?: {
                [key: string]: unknown;
            };
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** ProductOut */
        ProductOut: {
            /** Sku */
            sku: string;
            /** Slug */
            slug: string;
            /** Kind */
            kind: string;
            /** Brand */
            brand: string;
            /** Model */
            model: string;
            /** Mpn */
            mpn?: string | null;
            /**
             * Family
             * @default
             */
            family: string;
            /**
             * Condition
             * @default new
             */
            condition: string;
            /**
             * Segment
             * @default datacenter
             */
            segment: string;
            /**
             * Price Pkr
             * @default 0
             */
            price_pkr: number;
            /**
             * Price On Request
             * @default false
             */
            price_on_request: boolean;
            /**
             * Stock Qty
             * @default 0
             */
            stock_qty: number;
            /**
             * Lead Days
             * @default 0
             */
            lead_days: number;
            /**
             * Indent Only
             * @default false
             */
            indent_only: boolean;
            /**
             * Warranty Months
             * @default 12
             */
            warranty_months: number;
            /**
             * Release Year
             * @default 2024
             */
            release_year: number;
            /**
             * Search Key
             * @default
             */
            search_key: string;
            /** Highlights */
            highlights?: string[];
            /** Tags */
            tags?: string[];
            /** Specs */
            specs?: {
                [key: string]: unknown;
            };
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProductPage */
        ProductPage: {
            /** Items */
            items: components["schemas"]["ProductOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
        };
        /**
         * ProductUpdate
         * @description Every field optional, this is a PATCH, not a replace.
         */
        ProductUpdate: {
            /** Slug */
            slug?: string | null;
            /** Kind */
            kind?: string | null;
            /** Brand */
            brand?: string | null;
            /** Model */
            model?: string | null;
            /** Mpn */
            mpn?: string | null;
            /** Family */
            family?: string | null;
            /** Condition */
            condition?: string | null;
            /** Segment */
            segment?: string | null;
            /** Price Pkr */
            price_pkr?: number | null;
            /** Price On Request */
            price_on_request?: boolean | null;
            /** Stock Qty */
            stock_qty?: number | null;
            /** Lead Days */
            lead_days?: number | null;
            /** Indent Only */
            indent_only?: boolean | null;
            /** Warranty Months */
            warranty_months?: number | null;
            /** Release Year */
            release_year?: number | null;
            /** Search Key */
            search_key?: string | null;
            /** Highlights */
            highlights?: string[] | null;
            /** Tags */
            tags?: string[] | null;
            /** Specs */
            specs?: {
                [key: string]: unknown;
            } | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** QuoteCreate */
        QuoteCreate: {
            /** Contact Name */
            contact_name: string;
            /**
             * Contact Email
             * Format: email
             */
            contact_email: string;
            /** Organisation */
            organisation?: string | null;
            /** Phone */
            phone?: string | null;
            /** City */
            city?: string | null;
            /** Timeline */
            timeline?: string | null;
            /**
             * Target
             * @default desk
             */
            target: string;
            /** Workloads */
            workloads?: string[];
            /** Notes */
            notes?: string | null;
            /** Lines */
            lines?: components["schemas"]["QuoteLine"][];
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
            /** Findings */
            findings?: {
                [key: string]: unknown;
            }[];
        };
        /** QuoteLine */
        QuoteLine: {
            /** Sku */
            sku: string;
            /**
             * Qty
             * @default 1
             */
            qty: number;
            /**
             * Brand
             * @default
             */
            brand: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Kind
             * @default
             */
            kind: string;
            /**
             * Condition
             * @default
             */
            condition: string;
        };
        /** QuoteOut */
        QuoteOut: {
            /** Id */
            id: number;
            /** Reference */
            reference: string;
            /** Contact Name */
            contact_name: string;
            /**
             * Contact Email
             * Format: email
             */
            contact_email: string;
            /** Organisation */
            organisation: string | null;
            /** Phone */
            phone: string | null;
            /** City */
            city: string | null;
            /** Timeline */
            timeline: string | null;
            /** Target */
            target: string;
            /** Workloads */
            workloads: unknown[];
            /** Notes */
            notes: string | null;
            /** Lines */
            lines: unknown[];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Findings */
            findings: unknown[];
            status: components["schemas"]["QuoteStatus"];
            /** Internal Note */
            internal_note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QuotePage */
        QuotePage: {
            /** Items */
            items: components["schemas"]["QuoteOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
        };
        /**
         * QuoteStatus
         * @enum {string}
         */
        QuoteStatus: "new" | "in_review" | "quoted" | "won" | "lost";
        /** QuoteUpdate */
        QuoteUpdate: {
            status?: components["schemas"]["QuoteStatus"] | null;
            /** Internal Note */
            internal_note?: string | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description At least 8 characters.
             */
            password: string;
            /** Full Name */
            full_name?: string | null;
            /** Organisation */
            organisation?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "customer";
        /** Stats */
        Stats: {
            /** Products Total */
            products_total: number;
            /** Products Active */
            products_active: number;
            /** Products In Stock */
            products_in_stock: number;
            /** Quotes Total */
            quotes_total: number;
            /** Quotes New */
            quotes_new: number;
            /** Users Total */
            users_total: number;
            /** By Kind */
            by_kind: {
                [key: string]: number;
            };
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string | null;
            /** Organisation */
            organisation: string | null;
            /** Phone */
            phone: string | null;
            role: components["schemas"]["Role"];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_products_api_products_get: {
        parameters: {
            query?: {
                kind?: string | null;
                brand?: string | null;
                condition?: string | null;
                q?: string | null;
                in_stock?: boolean;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_products__sku__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_api_admin_products_get: {
        parameters: {
            query?: {
                kind?: string | null;
                q?: string | null;
                include_inactive?: boolean;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_admin_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_api_admin_products__sku__delete: {
        parameters: {
            query?: {
                hard?: boolean;
            };
            header?: never;
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_admin_products__sku__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_product_api_admin_products__sku__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_quote_api_quotes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_quotes_api_quotes_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"][];
                };
            };
        };
    };
    list_quotes_api_admin_quotes_get: {
        parameters: {
            query?: {
                status?: string | null;
                q?: string | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quote_api_admin_quotes__reference__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_quote_api_admin_quotes__reference__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
