import "server-only";
import { ensureReady } from "./init";
import { one, query } from "./client";
import type { CustomerRow, InvoiceRow, QuoteRow } from "./types";

export async function listCustomers(search=""):Promise<CustomerRow[]> { await ensureReady(); return query<CustomerRow>(`SELECT * FROM customers WHERE $1='' OR lower(coalesce(organisation,'')||' '||display_name||' '||coalesce(email,'')) LIKE '%'||lower($1)||'%' ORDER BY updated_at DESC LIMIT 250`,[search]); }
export async function getCustomer(id:number):Promise<CustomerRow|null> { await ensureReady(); return one<CustomerRow>("SELECT * FROM customers WHERE id=$1",[id]); }
export async function customerHistory(id:number):Promise<{quotes:QuoteRow[];invoices:InvoiceRow[];builds:Array<Record<string,unknown>>;support:Array<Record<string,unknown>>}> { await ensureReady(); const [quotes,invoices,builds,support]=await Promise.all([query<QuoteRow>("SELECT * FROM quotes WHERE customer_id=$1 ORDER BY created_at DESC",[id]),query<InvoiceRow>("SELECT * FROM invoices WHERE customer_id=$1 ORDER BY created_at DESC",[id]),query<Record<string,unknown>>("SELECT * FROM customer_saved_builds WHERE customer_id=$1 ORDER BY updated_at DESC",[id]),query<Record<string,unknown>>("SELECT * FROM customer_support_events WHERE customer_id=$1 ORDER BY created_at DESC",[id])]); return {quotes,invoices,builds,support}; }
export async function updateCustomer(id:number,patch:{display_name:string;organisation?:string;email?:string;phone?:string;ntn?:string;strn?:string;payment_terms?:string;internal_notes?:string;credit_limit_pkr:number}):Promise<void>{await ensureReady();await query(`UPDATE customers SET display_name=$1,organisation=$2,email=$3,phone=$4,ntn=$5,strn=$6,payment_terms=$7,internal_notes=$8,credit_limit_pkr=$9,updated_at=now() WHERE id=$10`,[patch.display_name,patch.organisation||null,patch.email||null,patch.phone||null,patch.ntn||null,patch.strn||null,patch.payment_terms||null,patch.internal_notes||null,patch.credit_limit_pkr,id]);}
