/**
 * Extended families.
 *
 * The first pass came out GPU-heavy, which made the configurator useless —
 * you cannot build a machine from 25 motherboards. This file fills in the
 * platform, power, thermal and fabric categories the builder actually needs,
 * and widens GPU coverage into the mid-range where most Pakistani orders sit.
 */

import type {
  ChassisFamily, CoolerFamily, CpuFamily, GpuFamily, MemFamily, MoboFamily,
  NicFamily, OpticFamily, PduFamily, PsuFamily, RackFamily, StorageFamily,
  SwitchFamily, SystemFamily, UpsFamily,
} from "./families";
import type { Condition, PcieGen, PcieSlot, PcieWidth } from "./types";

const RETAIL: Condition[] = ["new", "refurb-a", "refurb-b", "open-box"];
const LEGACY: Condition[] = ["refurb-a", "refurb-b", "recertified", "pull"];
const SERVER: Condition[] = ["new", "refurb-a", "recertified", "pull"];

const NV = ["ASUS", "MSI", "GIGABYTE", "ZOTAC", "Palit", "Inno3D", "Colorful", "PNY", "Galax"];
const AMDP = ["Sapphire", "PowerColor", "XFX", "ASRock", "GIGABYTE", "ASUS"];
const OEM = ["NVIDIA", "Dell", "HPE", "Supermicro", "Lenovo"];

const s = (gen: PcieGen, width: PcieWidth, lanes: PcieWidth, spacing = 2): PcieSlot => ({ gen, width, lanes, spacing });

/* ================================================================== GPUs */

export const GPUS_EXT: GpuFamily[] = [
  { key: "rtx-5070", brand: "NVIDIA", name: "GeForce RTX 5070 12GB", segment: "desktop", year: 2025, usd: 550, arch: "Blackwell", vramGb: 12, vramType: "gddr7", busBits: 192, bwGbs: 672, fp32: 30.9, bf16: 62, tdpW: 250, form: "pcie", slots: 2, lenMm: 280, pcieGen: 5, conn: ["12v2x6"], psuW: 650, nvlink: false, cooling: "axial", outputs: 4, ecc: false, mig: false, vgpu: false, partners: NV, conditions: ["new", "open-box"], highlights: ["12GB is the honest limit here — fine for 1440p gaming, tight for local models", "250W on a 650W unit", "DLSS 4 multi-frame generation"], tags: ["gaming", "value"] },
  { key: "rtx-5060ti-16", brand: "NVIDIA", name: "GeForce RTX 5060 Ti 16GB", segment: "desktop", year: 2025, usd: 430, arch: "Blackwell", vramGb: 16, vramType: "gddr7", busBits: 128, bwGbs: 448, fp32: 23.7, bf16: 47, tdpW: 180, form: "pcie", slots: 2, lenMm: 245, pcieGen: 5, conn: ["pcie-8"], psuW: 600, nvlink: false, cooling: "axial", outputs: 4, ecc: false, mig: false, vgpu: false, partners: NV, conditions: ["new", "open-box"], highlights: ["16GB on a 128-bit bus — capacity without the bandwidth to match", "Cheapest current card that will hold a 13B model", "180W, standard 8-pin"], tags: ["gaming", "value", "local-llm", "budget"] },
  { key: "rtx-4080s", brand: "NVIDIA", name: "GeForce RTX 4080 SUPER 16GB", segment: "desktop", year: 2024, usd: 1000, arch: "Ada Lovelace", vramGb: 16, vramType: "gddr6x", busBits: 256, bwGbs: 736, fp32: 52.2, bf16: 104, tdpW: 320, form: "pcie", slots: 3, lenMm: 310, pcieGen: 4, conn: ["12vhpwr"], psuW: 850, nvlink: false, cooling: "axial", outputs: 4, ecc: false, mig: false, vgpu: false, partners: NV, conditions: RETAIL, highlights: ["Still an excellent renderer", "320W", "Widely available used as gamers moved to 50-series"], tags: ["gaming", "creator", "value"] },
  { key: "rtx-4070ts", brand: "NVIDIA", name: "GeForce RTX 4070 Ti SUPER 16GB", segment: "desktop", year: 2024, usd: 800, arch: "Ada Lovelace", vramGb: 16, vramType: "gddr6x", busBits: 256, bwGbs: 672, fp32: 44.1, bf16: 88, tdpW: 285, form: "pcie", slots: 3, lenMm: 305, pcieGen: 4, conn: ["12vhpwr"], psuW: 750, nvlink: false, cooling: "axial", outputs: 4, ecc: false, mig: false, vgpu: false, partners: NV, conditions: RETAIL, highlights: ["16GB on a 256-bit bus, unlike the plain 4070 Ti", "285W", "The value pick for Blender and Stable Diffusion"], tags: ["gaming", "creator", "value"] },
  { key: "rtx-4060ti-16", brand: "NVIDIA", name: "GeForce RTX 4060 Ti 16GB", segment: "desktop", year: 2023, usd: 450, arch: "Ada Lovelace", vramGb: 16, vramType: "gddr6", busBits: 128, bwGbs: 288, fp32: 22.1, bf16: 44, tdpW: 165, form: "pcie", slots: 2, lenMm: 245, pcieGen: 4, conn: ["pcie-8"], psuW: 550, nvlink: false, cooling: "axial", outputs: 4, ecc: false, mig: false, vgpu: false, partners: NV, conditions: RETAIL, highlights: ["16GB for very little money; the 128-bit bus is the trade", "Only PCIe 4.0 x8 — pairs badly with older boards", "165W"], tags: ["budget", "local-llm", "value"] },
  { key: "rtx-3090ti", brand: "NVIDIA", name: "GeForce RTX 3090 Ti 24GB", segment: "desktop", year: 2022, usd: 950, arch: "Ampere", vramGb: 24, vramType: "gddr6x", busBits: 384, bwGbs: 1008, fp32: 40, bf16: 80, tdpW: 450, form: "pcie", slots: 3, lenMm: 320, pcieGen: 4, conn: ["12vhpwr"], psuW: 850, nvlink: false, cooling: "axial", outputs: 4, ecc: false, mig: false, vgpu: false, partners: NV, conditions: LEGACY, highlights: ["24GB with more bandwidth than a 3090", "450W and it will take all of it", "No NVLink, unlike the plain 3090"], tags: ["local-llm", "value", "high-power"] },
  { key: "rtx-3080", brand: "NVIDIA", name: "GeForce RTX 3080 10GB", segment: "desktop", year: 2020, usd: 420, arch: "Ampere", vramGb: 10, vramType: "gddr6x", busBits: 320, bwGbs: 760, fp32: 29.8, bf16: 60, tdpW: 320, form: "pcie", slots: 2, lenMm: 285, pcieGen: 4, conn: ["pcie-8", "pcie-8"], psuW: 750, nvlink: false, cooling: "axial", outputs: 4, ecc: false, mig: false, vgpu: false, partners: NV, conditions: LEGACY, highlights: ["Fast, but 10GB ages badly for anything but gaming", "Enormous mining-era supply in Pakistan — check the fans and pads", "320W"], tags: ["gaming", "budget", "value"] },
  { key: "rtx-3060-12", brand: "NVIDIA", name: "GeForce RTX 3060 12GB", segment: "desktop", year: 2021, usd: 250, arch: "Ampere", vramGb: 12, vramType: "gddr6", busBits: 192, bwGbs: 360, fp32: 12.7, bf16: 25, tdpW: 170, form: "pcie", slots: 2, lenMm: 242, pcieGen: 4, conn: ["pcie-8"], psuW: 550, nvlink: false, cooling: "axial", outputs: 4, ecc: false, mig: false, vgpu: false, partners: NV, conditions: LEGACY, highlights: ["12GB for less than any other CUDA card — the student's choice", "Slow, but it holds a 7B model comfortably", "170W"], tags: ["budget", "local-llm", "student", "value"] },
  { key: "rtx-a5000", brand: "NVIDIA", name: "RTX A5000 24GB", segment: "workstation", year: 2021, usd: 1700, arch: "Ampere", vramGb: 24, vramType: "gddr6", busBits: 384, bwGbs: 768, fp32: 27.8, bf16: 111, tdpW: 230, form: "pcie", slots: 2, lenMm: 267, pcieGen: 4, conn: ["eps-8"], psuW: 700, nvlink: true, cooling: "blower", outputs: 4, ecc: true, mig: false, vgpu: true, partners: ["NVIDIA", "PNY", "Leadtek"], conditions: LEGACY, highlights: ["24GB ECC with NVLink at 230W", "Blower design, four fit in a tower", "The most common workstation card on the PK refurb market"], tags: ["ecc", "nvlink", "value", "render"] },
  { key: "rtx-4500-ada", brand: "NVIDIA", name: "RTX 4500 Ada Generation 24GB", segment: "workstation", year: 2023, usd: 2400, arch: "Ada Lovelace", vramGb: 24, vramType: "gddr6", busBits: 192, bwGbs: 432, fp32: 39.6, bf16: 158, tdpW: 210, form: "pcie", slots: 2, lenMm: 267, pcieGen: 4, conn: ["12vhpwr"], psuW: 700, nvlink: false, cooling: "blower", outputs: 4, ecc: true, mig: false, vgpu: false, partners: ["NVIDIA", "PNY", "Leadtek"], conditions: ["new", "refurb-a", "open-box"], highlights: ["24GB ECC at 210W", "Blower exhaust", "No NVLink on Ada workstation cards — plan around it"], tags: ["ecc", "render", "cad"] },
  { key: "rtx-2000-ada", brand: "NVIDIA", name: "RTX 2000 Ada Generation 16GB", segment: "workstation", year: 2024, usd: 650, arch: "Ada Lovelace", vramGb: 16, vramType: "gddr6", busBits: 128, bwGbs: 224, fp32: 12, bf16: 48, tdpW: 70, form: "pcie", slots: 2, lenMm: 168, pcieGen: 4, conn: [], psuW: 400, nvlink: false, cooling: "axial", outputs: 4, ecc: true, mig: false, vgpu: false, partners: ["NVIDIA", "PNY", "Leadtek"], conditions: ["new", "open-box"], highlights: ["70W off the slot, no power cable, 16GB ECC", "Low-profile bracket in the box", "Drops into an SFF office machine"], tags: ["ecc", "low-profile", "efficient", "sff"] },
  { key: "tesla-t4", brand: "NVIDIA", name: "Tesla T4 16GB", segment: "datacenter", year: 2018, usd: 550, arch: "Turing", vramGb: 16, vramType: "gddr6", busBits: 256, bwGbs: 320, fp32: 8.1, bf16: 65, tdpW: 70, form: "pcie", slots: 1, lenMm: 168, pcieGen: 3, conn: [], psuW: 400, nvlink: false, cooling: "passive", outputs: 0, ecc: true, mig: false, vgpu: true, partners: OEM, conditions: LEGACY, highlights: ["70W single-slot passive — the original 1U inference card", "Still excellent for video transcode via NVENC", "PCIe 3.0 only"], tags: ["passive", "low-profile", "1u", "inference", "value", "transcode"] },
  { key: "tesla-v100", brand: "NVIDIA", name: "Tesla V100 SXM2 32GB", segment: "datacenter", year: 2018, usd: 900, arch: "Volta", vramGb: 32, vramType: "hbm2e", busBits: 4096, bwGbs: 900, fp32: 15.7, bf16: 125, tdpW: 300, form: "sxm", slots: 0, lenMm: 0, pcieGen: 3, conn: [], psuW: 0, nvlink: true, cooling: "liquid", outputs: 0, ecc: true, mig: false, vgpu: false, partners: OEM, conditions: ["refurb-a", "refurb-b", "pull"], highlights: ["32GB HBM2 for the price of a mid-range gaming card", "Needs an SXM2 baseboard — a DGX-1 or equivalent", "No BF16, no FP8; FP16 only"], tags: ["hbm", "nvlink", "value", "budget", "legacy"] },
  { key: "a16", brand: "NVIDIA", name: "A16 64GB", segment: "datacenter", year: 2021, usd: 2900, arch: "Ampere", vramGb: 64, vramType: "gddr6", busBits: 512, bwGbs: 800, fp32: 17.9, bf16: 36, tdpW: 250, form: "pcie", slots: 2, lenMm: 267, pcieGen: 4, conn: ["eps-8"], psuW: 750, nvlink: false, cooling: "passive", outputs: 0, ecc: true, mig: false, vgpu: true, partners: OEM, conditions: SERVER, highlights: ["Four GPUs on one card, 16GB each — built for VDI density", "64 concurrent virtual desktops per card", "Not a training card; the four dies do not cooperate"], tags: ["passive", "vdi", "vgpu", "density"] },
  { key: "rx-7900xt", brand: "AMD", name: "Radeon RX 7900 XT 20GB", segment: "desktop", year: 2022, usd: 700, arch: "RDNA 3", vramGb: 20, vramType: "gddr6", busBits: 320, bwGbs: 800, fp32: 51.6, bf16: 103, tdpW: 315, form: "pcie", slots: 3, lenMm: 276, pcieGen: 4, conn: ["pcie-8", "pcie-8"], psuW: 750, nvlink: false, cooling: "axial", outputs: 4, ecc: false, mig: false, vgpu: false, partners: AMDP, conditions: RETAIL, highlights: ["20GB, awkward middle child, priced accordingly", "Two standard 8-pins", "ROCm support is there but check your framework"], tags: ["gaming", "value", "rocm"] },
  { key: "rx-7800xt", brand: "AMD", name: "Radeon RX 7800 XT 16GB", segment: "desktop", year: 2023, usd: 500, arch: "RDNA 3", vramGb: 16, vramType: "gddr6", busBits: 256, bwGbs: 624, fp32: 37.3, bf16: 75, tdpW: 263, form: "pcie", slots: 2, lenMm: 267, pcieGen: 4, conn: ["pcie-8", "pcie-8"], psuW: 700, nvlink: false, cooling: "axial", outputs: 4, ecc: false, mig: false, vgpu: false, partners: AMDP, conditions: RETAIL, highlights: ["16GB at 1440p for well under NVIDIA money", "263W", "Dual slot, fits normal cases"], tags: ["gaming", "value"] },
  { key: "arc-b580", brand: "Intel", name: "Arc B580 12GB", segment: "desktop", year: 2024, usd: 250, arch: "Xe2 Battlemage", vramGb: 12, vramType: "gddr6", busBits: 192, bwGbs: 456, fp32: 13.6, bf16: 27, tdpW: 190, form: "pcie", slots: 2, lenMm: 272, pcieGen: 4, conn: ["pcie-8"], psuW: 550, nvlink: false, cooling: "axial", outputs: 4, ecc: false, mig: false, vgpu: false, partners: ["Intel", "ASRock", "Sparkle", "ACER"], conditions: ["new", "open-box"], highlights: ["12GB at this price is unmatched", "Needs Resizable BAR enabled or performance collapses", "AV1 encode in hardware"], tags: ["budget", "value", "av1"] },
  { key: "w7800", brand: "AMD", name: "Radeon PRO W7800 32GB", segment: "workstation", year: 2023, usd: 2500, arch: "RDNA 3", vramGb: 32, vramType: "gddr6", busBits: 256, bwGbs: 576, fp32: 45.2, bf16: 90, tdpW: 260, form: "pcie", slots: 2, lenMm: 267, pcieGen: 4, conn: ["pcie-8", "pcie-8"], psuW: 750, nvlink: false, cooling: "blower", outputs: 4, ecc: true, mig: false, vgpu: false, partners: ["AMD", "Sapphire"], conditions: ["new", "refurb-a", "open-box"], highlights: ["32GB ECC, dual-slot blower", "Half the price of the equivalent NVIDIA card", "ROCm 6 on Linux"], tags: ["ecc", "render", "rocm", "value"] },
];

/* ================================================================== CPUs */

export const CPUS_EXT: CpuFamily[] = [
  { key: "epyc-9965", brand: "AMD", name: "EPYC 9965", segment: "datacenter", year: 2024, usd: 14813, socket: "SP5", arch: "Zen 5c (Turin Dense)", cores: 192, threads: 384, base: 2.25, boost: 3.7, l3: 384, tdpW: 500, maxW: 500, memGen: "ddr5", memCh: 12, memKinds: ["rdimm"], maxMemGb: 6144, memMts: 6000, ecc: true, pcieGen: 5, lanes: 128, maxSockets: 2, igpu: false, boxed: false, avx512: true, amx: false, conditions: ["new"], highlights: ["192 dense cores per socket, 384 in a 2P node", "Zen 5c: lower clocks, far more cores per watt", "500W — liquid cooling in anything under 4U"], tags: ["dense", "flagship", "hpc"] },
  { key: "epyc-9575f", brand: "AMD", name: "EPYC 9575F", segment: "datacenter", year: 2024, usd: 11048, socket: "SP5", arch: "Zen 5 (Turin)", cores: 64, threads: 128, base: 3.3, boost: 5.0, l3: 256, tdpW: 400, maxW: 400, memGen: "ddr5", memCh: 12, memKinds: ["rdimm"], maxMemGb: 6144, memMts: 6000, ecc: true, pcieGen: 5, lanes: 128, maxSockets: 2, igpu: false, boxed: false, avx512: true, amx: false, conditions: ["new"], highlights: ["5.0GHz boost on a server socket — the GPU-node head CPU", "High clocks matter when you are feeding eight accelerators", "400W"], tags: ["gpu-host", "high-clock", "flagship"] },
  { key: "epyc-9354p", brand: "AMD", name: "EPYC 9354P", segment: "datacenter", year: 2022, usd: 2730, socket: "SP5", arch: "Zen 4 (Genoa)", cores: 32, threads: 64, base: 3.25, boost: 3.8, l3: 256, tdpW: 280, maxW: 320, memGen: "ddr5", memCh: 12, memKinds: ["rdimm"], maxMemGb: 6144, memMts: 4800, ecc: true, pcieGen: 5, lanes: 128, maxSockets: 1, igpu: false, boxed: false, avx512: true, amx: false, conditions: SERVER, highlights: ["Single-socket-only P variant, meaningfully cheaper than the 9354", "Same 128 lanes and 12 channels", "If you were never going 2P, buy the P"], tags: ["gpu-host", "value", "single-socket"] },
  { key: "epyc-9124", brand: "AMD", name: "EPYC 9124", segment: "datacenter", year: 2022, usd: 1083, socket: "SP5", arch: "Zen 4 (Genoa)", cores: 16, threads: 32, base: 3.0, boost: 3.7, l3: 64, tdpW: 200, maxW: 240, memGen: "ddr5", memCh: 12, memKinds: ["rdimm"], maxMemGb: 6144, memMts: 4800, ecc: true, pcieGen: 5, lanes: 128, maxSockets: 2, igpu: false, boxed: false, avx512: true, amx: false, conditions: SERVER, highlights: ["The cheapest route to 12-channel DDR5 and 128 PCIe 5.0 lanes", "16 cores is plenty for a storage or fabric node", "200W"], tags: ["value", "storage-host", "budget"] },
  { key: "epyc-9474f", brand: "AMD", name: "EPYC 9474F", segment: "datacenter", year: 2022, usd: 6780, socket: "SP5", arch: "Zen 4 (Genoa)", cores: 48, threads: 96, base: 3.6, boost: 4.1, l3: 256, tdpW: 360, maxW: 400, memGen: "ddr5", memCh: 12, memKinds: ["rdimm"], maxMemGb: 6144, memMts: 4800, ecc: true, pcieGen: 5, lanes: 128, maxSockets: 2, igpu: false, boxed: false, avx512: true, amx: false, conditions: ["new", "refurb-a", "pull"], highlights: ["Frequency-optimised 48 core — good balance for CFD", "3.6GHz all-core base", "360W"], tags: ["hpc", "high-clock", "cfd"] },
  { key: "epyc-7713", brand: "AMD", name: "EPYC 7713", segment: "datacenter", year: 2021, usd: 2200, socket: "SP3", arch: "Zen 3 (Milan)", cores: 64, threads: 128, base: 2.0, boost: 3.675, l3: 256, tdpW: 225, maxW: 240, memGen: "ddr4", memCh: 8, memKinds: ["rdimm", "lrdimm"], maxMemGb: 4096, memMts: 3200, ecc: true, pcieGen: 4, lanes: 128, maxSockets: 2, igpu: false, boxed: false, avx512: false, amx: false, conditions: LEGACY, highlights: ["64 cores at 225W — the efficient Milan part", "Cheaper than a 7763 for 90% of the throughput", "Abundant used"], tags: ["value", "dense", "hpc"] },
  { key: "epyc-7313", brand: "AMD", name: "EPYC 7313", segment: "datacenter", year: 2021, usd: 600, socket: "SP3", arch: "Zen 3 (Milan)", cores: 16, threads: 32, base: 3.0, boost: 3.7, l3: 128, tdpW: 155, maxW: 180, memGen: "ddr4", memCh: 8, memKinds: ["rdimm", "lrdimm"], maxMemGb: 4096, memMts: 3200, ecc: true, pcieGen: 4, lanes: 128, maxSockets: 2, igpu: false, boxed: false, avx512: false, amx: false, conditions: LEGACY, highlights: ["16 cores, 128 lanes, 155W — a superb cheap GPU host", "8-channel DDR4 keeps the memory bill low", "The homelab EPYC of choice"], tags: ["value", "budget", "gpu-host", "homelab"] },
  { key: "epyc-7502", brand: "AMD", name: "EPYC 7502", segment: "datacenter", year: 2019, usd: 480, socket: "SP3", arch: "Zen 2 (Rome)", cores: 32, threads: 64, base: 2.5, boost: 3.35, l3: 128, tdpW: 180, maxW: 200, memGen: "ddr4", memCh: 8, memKinds: ["rdimm", "lrdimm"], maxMemGb: 4096, memMts: 3200, ecc: true, pcieGen: 4, lanes: 128, maxSockets: 2, igpu: false, boxed: false, avx512: false, amx: false, conditions: LEGACY, highlights: ["32 Rome cores for the price of a mid-range GPU", "Confirm the board has a Rome-capable BIOS before ordering", "180W"], tags: ["value", "budget", "dense"] },
  { key: "xeon-6548y", brand: "Intel", name: "Xeon Gold 6548Y+", segment: "datacenter", year: 2023, usd: 3400, socket: "LGA4677", arch: "Emerald Rapids", cores: 32, threads: 64, base: 2.5, boost: 4.1, l3: 60, tdpW: 250, maxW: 300, memGen: "ddr5", memCh: 8, memKinds: ["rdimm"], maxMemGb: 4096, memMts: 5600, ecc: true, pcieGen: 5, lanes: 80, maxSockets: 2, igpu: false, boxed: false, avx512: true, amx: true, conditions: ["new", "refurb-a"], highlights: ["32 cores, DDR5-5600, AMX", "250W", "Good balance for mixed virtualisation and inference"], tags: ["amx", "balanced", "virtualisation"] },
  { key: "xeon-8468", brand: "Intel", name: "Xeon Platinum 8468", segment: "datacenter", year: 2023, usd: 7200, socket: "LGA4677", arch: "Sapphire Rapids", cores: 48, threads: 96, base: 2.1, boost: 3.8, l3: 105, tdpW: 350, maxW: 420, memGen: "ddr5", memCh: 8, memKinds: ["rdimm"], maxMemGb: 4096, memMts: 4800, ecc: true, pcieGen: 5, lanes: 80, maxSockets: 2, igpu: false, boxed: false, avx512: true, amx: true, conditions: ["new", "refurb-a", "pull"], highlights: ["48 cores with AMX", "80 PCIe 5.0 lanes", "Prices on the secondary market have collapsed"], tags: ["amx", "value", "hpc"] },
  { key: "xeon-5416s", brand: "Intel", name: "Xeon Silver 5416S", segment: "datacenter", year: 2023, usd: 1050, socket: "LGA4677", arch: "Sapphire Rapids", cores: 16, threads: 32, base: 2.0, boost: 4.0, l3: 30, tdpW: 150, maxW: 190, memGen: "ddr5", memCh: 8, memKinds: ["rdimm"], maxMemGb: 4096, memMts: 4400, ecc: true, pcieGen: 5, lanes: 80, maxSockets: 2, igpu: false, boxed: false, avx512: true, amx: true, conditions: SERVER, highlights: ["Cheapest LGA4677 part with AMX", "150W, easy in 1U", "8-channel DDR5 even at Silver tier"], tags: ["amx", "budget", "value"] },
  { key: "xeon-6230", brand: "Intel", name: "Xeon Gold 6230", segment: "datacenter", year: 2019, usd: 260, socket: "LGA3647", arch: "Cascade Lake", cores: 20, threads: 40, base: 2.1, boost: 3.9, l3: 27.5, tdpW: 125, maxW: 150, memGen: "ddr4", memCh: 6, memKinds: ["rdimm", "lrdimm"], maxMemGb: 1024, memMts: 2933, ecc: true, pcieGen: 3, lanes: 48, maxSockets: 4, igpu: false, boxed: false, avx512: true, amx: false, conditions: LEGACY, highlights: ["20 cores at 125W", "Very common in decommissioned Dell R740 and HPE DL380 fleets", "PCIe 3.0 — CPU work only"], tags: ["value", "budget", "cpu-compute"] },
  { key: "xeon-4214", brand: "Intel", name: "Xeon Silver 4214", segment: "datacenter", year: 2019, usd: 110, socket: "LGA3647", arch: "Cascade Lake", cores: 12, threads: 24, base: 2.2, boost: 3.2, l3: 16.5, tdpW: 85, maxW: 105, memGen: "ddr4", memCh: 6, memKinds: ["rdimm", "lrdimm"], maxMemGb: 1024, memMts: 2400, ecc: true, pcieGen: 3, lanes: 48, maxSockets: 2, igpu: false, boxed: false, avx512: true, amx: false, conditions: LEGACY, highlights: ["85W, 12 cores — a genuinely cheap ECC lab machine", "Very cheap as a tested pull", "Do not expect much per-core speed"], tags: ["budget", "homelab", "value"] },
  { key: "xeon-e5-2699v4", brand: "Intel", name: "Xeon E5-2699 v4", segment: "datacenter", year: 2016, usd: 90, socket: "LGA2011-3", arch: "Broadwell-EP", cores: 22, threads: 44, base: 2.2, boost: 3.6, l3: 55, tdpW: 145, maxW: 160, memGen: "ddr4", memCh: 4, memKinds: ["rdimm", "lrdimm"], maxMemGb: 1536, memMts: 2400, ecc: true, pcieGen: 3, lanes: 40, maxSockets: 2, igpu: false, boxed: false, avx512: false, amx: false, conditions: ["refurb-a", "refurb-b", "pull"], highlights: ["44 threads per socket for pocket change", "88 threads in a dual-socket board", "PCIe 3.0, DDR4-2400 — a lab machine, not a production node"], tags: ["budget", "homelab", "value"] },
  { key: "tr-7985wx", brand: "AMD", name: "Ryzen Threadripper PRO 7985WX", segment: "workstation", year: 2023, usd: 7349, socket: "sTR5", arch: "Zen 4 (Storm Peak)", cores: 64, threads: 128, base: 3.2, boost: 5.1, l3: 256, tdpW: 350, maxW: 400, memGen: "ddr5", memCh: 8, memKinds: ["rdimm"], maxMemGb: 2048, memMts: 5200, ecc: true, pcieGen: 5, lanes: 128, maxSockets: 1, igpu: false, boxed: true, avx512: true, amx: false, conditions: ["new", "refurb-a"], highlights: ["64 cores and 128 PCIe 5.0 lanes", "Better clocks than the 96-core part for most simulation work", "350W — plan a 360mm AIO or the Noctua sTR5 tower"], tags: ["gpu-host", "workstation", "flagship"] },
  { key: "tr-7965wx", brand: "AMD", name: "Ryzen Threadripper PRO 7965WX", segment: "workstation", year: 2023, usd: 2649, socket: "sTR5", arch: "Zen 4 (Storm Peak)", cores: 24, threads: 48, base: 4.2, boost: 5.3, l3: 128, tdpW: 350, maxW: 400, memGen: "ddr5", memCh: 8, memKinds: ["rdimm"], maxMemGb: 2048, memMts: 5200, ecc: true, pcieGen: 5, lanes: 128, maxSockets: 1, igpu: false, boxed: true, avx512: true, amx: false, conditions: ["new", "refurb-a"], highlights: ["Cheapest way into 128 PCIe 5.0 lanes and 8-channel ECC", "4.2GHz all-core base", "If you need slots more than cores, this is the part"], tags: ["gpu-host", "workstation", "value"] },
  { key: "tr-5975wx", brand: "AMD", name: "Ryzen Threadripper PRO 5975WX", segment: "workstation", year: 2022, usd: 1100, socket: "sWRX8", arch: "Zen 3 (Chagall)", cores: 32, threads: 64, base: 3.6, boost: 4.5, l3: 128, tdpW: 280, maxW: 320, memGen: "ddr4", memCh: 8, memKinds: ["rdimm"], maxMemGb: 2048, memMts: 3200, ecc: true, pcieGen: 4, lanes: 128, maxSockets: 1, igpu: false, boxed: true, avx512: false, amx: false, conditions: LEGACY, highlights: ["128 PCIe 4.0 lanes on DDR4 pricing", "The value multi-GPU workstation platform", "280W"], tags: ["gpu-host", "workstation", "value", "budget"] },
  { key: "xeon-w7-3465x", brand: "Intel", name: "Xeon w7-3465X", segment: "workstation", year: 2023, usd: 2889, socket: "LGA4677", arch: "Sapphire Rapids-WS", cores: 28, threads: 56, base: 2.5, boost: 4.8, l3: 75, tdpW: 300, maxW: 360, memGen: "ddr5", memCh: 8, memKinds: ["rdimm"], maxMemGb: 4096, memMts: 4800, ecc: true, pcieGen: 5, lanes: 112, maxSockets: 1, igpu: false, boxed: true, avx512: true, amx: true, conditions: ["new", "refurb-a"], highlights: ["112 PCIe 5.0 lanes with AMX on a workstation board", "28 cores at 4.8GHz boost", "300W"], tags: ["amx", "workstation", "gpu-host"] },
  { key: "r9-9900x", brand: "AMD", name: "Ryzen 9 9900X", segment: "desktop", year: 2024, usd: 449, socket: "AM5", arch: "Zen 5", cores: 12, threads: 24, base: 4.4, boost: 5.6, l3: 64, tdpW: 120, maxW: 162, memGen: "ddr5", memCh: 2, memKinds: ["udimm"], maxMemGb: 192, memMts: 5600, ecc: true, pcieGen: 5, lanes: 28, maxSockets: 1, igpu: true, boxed: true, avx512: true, amx: false, conditions: ["new", "open-box"], highlights: ["12 Zen 5 cores at 120W", "Full AVX-512", "Unbuffered ECC on most AM5 boards"], tags: ["desktop", "creator", "value"] },
  { key: "r9-7950x", brand: "AMD", name: "Ryzen 9 7950X", segment: "desktop", year: 2022, usd: 400, socket: "AM5", arch: "Zen 4", cores: 16, threads: 32, base: 4.5, boost: 5.7, l3: 64, tdpW: 170, maxW: 230, memGen: "ddr5", memCh: 2, memKinds: ["udimm"], maxMemGb: 192, memMts: 5200, ecc: true, pcieGen: 5, lanes: 28, maxSockets: 1, igpu: true, boxed: true, avx512: true, amx: false, conditions: RETAIL, highlights: ["16 cores, now well discounted since Zen 5 landed", "170W but it will happily sit at 95C by design", "AVX-512"], tags: ["desktop", "creator", "value"] },
  { key: "r7-7700x", brand: "AMD", name: "Ryzen 7 7700X", segment: "desktop", year: 2022, usd: 280, socket: "AM5", arch: "Zen 4", cores: 8, threads: 16, base: 4.5, boost: 5.4, l3: 32, tdpW: 105, maxW: 142, memGen: "ddr5", memCh: 2, memKinds: ["udimm"], maxMemGb: 192, memMts: 5200, ecc: true, pcieGen: 5, lanes: 28, maxSockets: 1, igpu: true, boxed: true, avx512: true, amx: false, conditions: RETAIL, highlights: ["Sensible 8-core AM5 entry", "105W", "Upgrade path to Zen 5 on the same board"], tags: ["desktop", "value", "budget"] },
  { key: "r5-7600", brand: "AMD", name: "Ryzen 5 7600", segment: "desktop", year: 2022, usd: 200, socket: "AM5", arch: "Zen 4", cores: 6, threads: 12, base: 3.8, boost: 5.1, l3: 32, tdpW: 65, maxW: 88, memGen: "ddr5", memCh: 2, memKinds: ["udimm"], maxMemGb: 192, memMts: 5200, ecc: true, pcieGen: 5, lanes: 28, maxSockets: 1, igpu: true, boxed: true, avx512: true, amx: false, conditions: RETAIL, highlights: ["65W, cooler in the box", "The budget AM5 starting point", "Integrated graphics for headless setup"], tags: ["desktop", "budget", "value"] },
  { key: "i7-14700k", brand: "Intel", name: "Core i7-14700K", segment: "desktop", year: 2023, usd: 400, socket: "LGA1700", arch: "Raptor Lake Refresh", cores: 20, threads: 28, base: 3.4, boost: 5.6, l3: 33, tdpW: 125, maxW: 253, memGen: "ddr5", memCh: 2, memKinds: ["udimm"], maxMemGb: 192, memMts: 5600, ecc: false, pcieGen: 5, lanes: 20, maxSockets: 1, igpu: true, boxed: true, avx512: false, amx: false, conditions: RETAIL, highlights: ["20 cores for the money", "253W peak — do not undersize the cooler", "Apply the microcode fix before sustained load"], tags: ["desktop", "value"] },
  { key: "ultra9-285k", brand: "Intel", name: "Core Ultra 9 285K", segment: "desktop", year: 2024, usd: 589, socket: "LGA1851", arch: "Arrow Lake", cores: 24, threads: 24, base: 3.7, boost: 5.7, l3: 36, tdpW: 125, maxW: 250, memGen: "ddr5", memCh: 2, memKinds: ["udimm"], maxMemGb: 192, memMts: 6400, ecc: false, pcieGen: 5, lanes: 24, maxSockets: 1, igpu: true, boxed: true, avx512: false, amx: false, conditions: ["new", "open-box"], highlights: ["No hyperthreading — 24 cores, 24 threads", "Much cooler than the 14900K it replaces", "New LGA1851 socket, no upgrade path from 1700"], tags: ["desktop", "efficient"] },
];

/* ========================================================== Motherboards */

export const MOBOS_EXT: MoboFamily[] = [
  { key: "h13ssl-nt", brand: "Supermicro", name: "H13SSL-NT", segment: "datacenter", year: 2023, usd: 900, socket: "SP5", sockets: 1, chipset: "AMD SoC", form: "atx", memGen: "ddr5", memSlots: 12, memKinds: ["rdimm"], maxMemGb: 3072, memMts: 4800, ecc: true, slots: [s(5,16,16,2), s(5,16,16,2), s(5,16,8,1), s(5,8,8,1), s(5,16,16,2)], m2: 2, m2Gen: 5, sata: 8, u2: 2, eps: 2, nicGbps: 10, nicPorts: 2, ipmi: true, vrm: 16, flashback: false, conditions: SERVER, highlights: ["Dual 10GBase-T onboard, saving a slot", "12 DDR5 channels on ATX", "IPMI 2.0 with dedicated LAN"], tags: ["ipmi", "single-socket", "atx", "10gbe"] },
  { key: "h13dsh", brand: "Supermicro", name: "H13DSH Dual SP5", segment: "datacenter", year: 2023, usd: 1450, socket: "SP5", sockets: 2, chipset: "AMD SoC", form: "eatx", memGen: "ddr5", memSlots: 24, memKinds: ["rdimm"], maxMemGb: 6144, memMts: 4800, ecc: true, slots: [s(5,16,16,2), s(5,16,16,2), s(5,16,16,2), s(5,16,16,2), s(5,16,16,2), s(5,8,8,1)], m2: 2, m2Gen: 5, sata: 10, u2: 4, eps: 4, nicGbps: 10, nicPorts: 2, ipmi: true, vrm: 20, flashback: false, conditions: ["new", "refurb-a"], highlights: ["24 DIMM slots, 6TB across two sockets", "Five full x16 PCIe 5.0 slots", "Four EPS headers — two per socket, both required"], tags: ["ipmi", "dual-socket", "eatx", "large-memory"] },
  { key: "h12ssl-nt", brand: "Supermicro", name: "H12SSL-NT", segment: "datacenter", year: 2020, usd: 620, socket: "SP3", sockets: 1, chipset: "AMD SoC", form: "atx", memGen: "ddr4", memSlots: 8, memKinds: ["rdimm", "lrdimm"], maxMemGb: 2048, memMts: 3200, ecc: true, slots: [s(4,16,16,2), s(4,16,16,2), s(4,16,8,1), s(4,8,8,1), s(4,16,16,2)], m2: 2, m2Gen: 4, sata: 8, u2: 2, eps: 2, nicGbps: 10, nicPorts: 2, ipmi: true, vrm: 16, flashback: false, conditions: LEGACY, highlights: ["Dual 10GBase-T version of the H12SSL", "Takes any Rome or Milan EPYC", "The default cheap 128-lane board"], tags: ["ipmi", "single-socket", "atx", "10gbe", "value"] },
  { key: "h12dsi-n6", brand: "Supermicro", name: "H12DSi-N6 Dual SP3", segment: "datacenter", year: 2020, usd: 780, socket: "SP3", sockets: 2, chipset: "AMD SoC", form: "eatx", memGen: "ddr4", memSlots: 16, memKinds: ["rdimm", "lrdimm"], maxMemGb: 4096, memMts: 3200, ecc: true, slots: [s(4,16,16,2), s(4,16,16,2), s(4,16,16,2), s(4,16,16,2), s(4,8,8,1), s(4,16,8,1)], m2: 2, m2Gen: 4, sata: 16, u2: 2, eps: 4, nicGbps: 1, nicPorts: 2, ipmi: true, vrm: 16, flashback: false, conditions: LEGACY, highlights: ["128 cores in one board with two 7763s", "16 DIMMs, 4TB", "Very good value used"], tags: ["ipmi", "dual-socket", "eatx", "value", "dense"] },
  { key: "mz73-lm0", brand: "GIGABYTE", name: "MZ73-LM0 Dual SP5", segment: "datacenter", year: 2023, usd: 1550, socket: "SP5", sockets: 2, chipset: "AMD SoC", form: "eatx", memGen: "ddr5", memSlots: 24, memKinds: ["rdimm"], maxMemGb: 6144, memMts: 4800, ecc: true, slots: [s(5,16,16,2), s(5,16,16,2), s(5,16,16,2), s(5,16,16,2), s(5,16,16,2)], m2: 2, m2Gen: 5, sata: 4, u2: 8, eps: 4, nicGbps: 10, nicPorts: 2, ipmi: true, vrm: 20, flashback: false, conditions: ["new", "refurb-a"], highlights: ["Eight U.2 ports direct from the CPU — no HBA needed", "384 cores with two 9965s", "Dual 10GbE"], tags: ["ipmi", "dual-socket", "eatx", "nvme", "dense"] },
  { key: "mz33-ar0", brand: "GIGABYTE", name: "MZ33-AR0", segment: "datacenter", year: 2023, usd: 820, socket: "SP5", sockets: 1, chipset: "AMD SoC", form: "eatx", memGen: "ddr5", memSlots: 24, memKinds: ["rdimm"], maxMemGb: 6144, memMts: 4800, ecc: true, slots: [s(5,16,16,2), s(5,16,16,2), s(5,16,16,2), s(5,16,16,2)], m2: 2, m2Gen: 5, sata: 4, u2: 8, eps: 2, nicGbps: 1, nicPorts: 2, ipmi: true, vrm: 18, flashback: false, conditions: SERVER, highlights: ["24 DIMMs on a single socket — 6TB on one CPU", "Two DIMMs per channel", "Four full x16 slots"], tags: ["ipmi", "single-socket", "eatx", "large-memory"] },
  { key: "x13sei-tf", brand: "Supermicro", name: "X13SEI-TF", segment: "datacenter", year: 2023, usd: 780, socket: "LGA4677", sockets: 1, chipset: "Intel C741", form: "atx", memGen: "ddr5", memSlots: 8, memKinds: ["rdimm"], maxMemGb: 2048, memMts: 4800, ecc: true, slots: [s(5,16,16,2), s(5,16,16,2), s(5,16,8,1), s(5,8,8,1)], m2: 2, m2Gen: 4, sata: 8, u2: 2, eps: 2, nicGbps: 10, nicPorts: 2, ipmi: true, vrm: 16, flashback: false, conditions: SERVER, highlights: ["Single-socket Sapphire/Emerald Rapids on ATX", "Dual 10GBase-T", "AMX-capable with the right CPU"], tags: ["ipmi", "single-socket", "atx", "amx", "10gbe"] },
  { key: "x12dpi-nt6", brand: "Supermicro", name: "X12DPi-NT6", segment: "datacenter", year: 2021, usd: 650, socket: "LGA4189", sockets: 2, chipset: "Intel C621A", form: "eatx", memGen: "ddr4", memSlots: 16, memKinds: ["rdimm", "lrdimm"], maxMemGb: 4096, memMts: 3200, ecc: true, slots: [s(4,16,16,2), s(4,16,16,2), s(4,16,16,2), s(4,8,8,1), s(4,16,8,1)], m2: 2, m2Gen: 4, sata: 14, u2: 4, eps: 4, nicGbps: 10, nicPorts: 2, ipmi: true, vrm: 16, flashback: false, conditions: LEGACY, highlights: ["Dual Ice Lake Xeon, PCIe 4.0", "8-channel DDR4 per socket", "The last good DDR4 Intel server platform"], tags: ["ipmi", "dual-socket", "eatx", "value"] },
  { key: "trx50-aero", brand: "GIGABYTE", name: "TRX50 AERO D", segment: "workstation", year: 2023, usd: 750, socket: "sTR5", sockets: 1, chipset: "AMD TRX50", form: "eatx", memGen: "ddr5", memSlots: 4, memKinds: ["rdimm"], maxMemGb: 1024, memMts: 5200, ecc: true, slots: [s(5,16,16,2), s(5,16,16,2), s(5,16,8,2), s(4,16,4,2)], m2: 4, m2Gen: 5, sata: 4, u2: 0, eps: 2, nicGbps: 10, nicPorts: 1, ipmi: false, vrm: 16, flashback: true, conditions: ["new", "refurb-a", "open-box"], highlights: ["TRX50: four memory channels, not eight — cheaper board, less bandwidth", "Still 128 PCIe 5.0 lanes from the CPU", "10GbE plus 2.5GbE"], tags: ["workstation", "eatx", "value"] },
  { key: "wrx80e-sage", brand: "ASUS", name: "Pro WS WRX80E-SAGE SE WIFI", segment: "workstation", year: 2021, usd: 900, socket: "sWRX8", sockets: 1, chipset: "AMD WRX80", form: "eatx", memGen: "ddr4", memSlots: 8, memKinds: ["rdimm"], maxMemGb: 2048, memMts: 3200, ecc: true, slots: [s(4,16,16,2), s(4,16,16,2), s(4,16,16,2), s(4,16,16,2), s(4,16,16,2), s(4,16,16,2), s(4,16,16,2)], m2: 3, m2Gen: 4, sata: 8, u2: 0, eps: 3, nicGbps: 10, nicPorts: 2, ipmi: true, vrm: 16, flashback: true, conditions: LEGACY, highlights: ["Seven x16 PCIe 4.0 slots, all electrically full width", "The classic four-GPU workstation board", "Dual 10GbE and a BMC"], tags: ["gpu-host", "eatx", "workstation", "value", "dense"] },
  { key: "w790-sage", brand: "ASUS", name: "Pro WS W790E-SAGE SE", segment: "workstation", year: 2023, usd: 1200, socket: "LGA4677", sockets: 1, chipset: "Intel W790", form: "eatx", memGen: "ddr5", memSlots: 8, memKinds: ["rdimm"], maxMemGb: 2048, memMts: 4800, ecc: true, slots: [s(5,16,16,2), s(5,16,16,2), s(5,16,16,2), s(5,16,16,2), s(5,16,16,2), s(5,16,8,2), s(5,16,8,2)], m2: 4, m2Gen: 5, sata: 8, u2: 0, eps: 3, nicGbps: 10, nicPorts: 2, ipmi: true, vrm: 16, flashback: true, conditions: ["new", "refurb-a"], highlights: ["Seven slots, 8-channel DDR5 RDIMM, AMX-capable", "Dual 10GbE plus BMC", "The Intel answer to WRX90"], tags: ["gpu-host", "eatx", "workstation", "amx"] },
  { key: "x670e-taichi", brand: "ASRock", name: "X670E Taichi", segment: "desktop", year: 2022, usd: 480, socket: "AM5", sockets: 1, chipset: "AMD X670E", form: "eatx", memGen: "ddr5", memSlots: 4, memKinds: ["udimm"], maxMemGb: 192, memMts: 6600, ecc: true, slots: [s(5,16,16,3), s(5,16,8,2), s(4,16,4,2)], m2: 4, m2Gen: 5, sata: 8, u2: 0, eps: 2, nicGbps: 2.5, nicPorts: 1, ipmi: false, vrm: 24, flashback: true, conditions: RETAIL, highlights: ["24+2+1 VRM, absurd for a desktop board and very welcome", "Four M.2, two at Gen5", "ECC UDIMM passes through"], tags: ["desktop", "eatx", "enthusiast"] },
  { key: "b650-tomahawk", brand: "MSI", name: "MAG B650 TOMAHAWK WIFI", segment: "desktop", year: 2022, usd: 220, socket: "AM5", sockets: 1, chipset: "AMD B650", form: "atx", memGen: "ddr5", memSlots: 4, memKinds: ["udimm"], maxMemGb: 192, memMts: 6400, ecc: true, slots: [s(4,16,16,3), s(3,16,4,2)], m2: 3, m2Gen: 5, sata: 6, u2: 0, eps: 2, nicGbps: 2.5, nicPorts: 1, ipmi: false, vrm: 14, flashback: true, conditions: RETAIL, highlights: ["The sensible AM5 board — everything you need, nothing you do not", "Handles a 9950X without VRM throttling", "BIOS Flashback"], tags: ["desktop", "atx", "value"] },
  { key: "b650m-ds3h", brand: "GIGABYTE", name: "B650M DS3H", segment: "desktop", year: 2022, usd: 130, socket: "AM5", sockets: 1, chipset: "AMD B650", form: "matx", memGen: "ddr5", memSlots: 4, memKinds: ["udimm"], maxMemGb: 128, memMts: 6000, ecc: false, slots: [s(4,16,16,3), s(3,16,4,2)], m2: 2, m2Gen: 4, sata: 4, u2: 0, eps: 1, nicGbps: 1, nicPorts: 1, ipmi: false, vrm: 8, flashback: false, conditions: RETAIL, highlights: ["Budget mATX AM5", "One EPS header — do not put a 170W chip on it and expect miracles", "No Gen5 M.2"], tags: ["desktop", "matx", "budget"] },
  { key: "z890-carbon", brand: "MSI", name: "MPG Z890 CARBON WIFI", segment: "desktop", year: 2024, usd: 500, socket: "LGA1851", sockets: 1, chipset: "Intel Z890", form: "atx", memGen: "ddr5", memSlots: 4, memKinds: ["udimm"], maxMemGb: 256, memMts: 8000, ecc: false, slots: [s(5,16,16,3), s(4,16,4,2)], m2: 5, m2Gen: 5, sata: 4, u2: 0, eps: 2, nicGbps: 5, nicPorts: 1, ipmi: false, vrm: 18, flashback: true, conditions: ["new", "open-box"], highlights: ["Arrow Lake platform, DDR5-8000 supported", "Five M.2 slots", "Thunderbolt 4 onboard"], tags: ["desktop", "atx", "enthusiast"] },
  { key: "z790-tomahawk", brand: "MSI", name: "MAG Z790 TOMAHAWK WIFI", segment: "desktop", year: 2022, usd: 300, socket: "LGA1700", sockets: 1, chipset: "Intel Z790", form: "atx", memGen: "ddr5", memSlots: 4, memKinds: ["udimm"], maxMemGb: 192, memMts: 7200, ecc: false, slots: [s(5,16,16,3), s(4,16,4,2), s(3,16,4,2)], m2: 4, m2Gen: 5, sata: 6, u2: 0, eps: 2, nicGbps: 2.5, nicPorts: 1, ipmi: false, vrm: 18, flashback: true, conditions: RETAIL, highlights: ["Solid 14700K/14900K board", "18-phase VRM, adequate for 253W", "Four M.2"], tags: ["desktop", "atx", "value"] },
];

/* ================================================================ Memory */

export const MEMORY_EXT: MemFamily[] = [
  { key: "sk-ddr5-rdimm-6400", brand: "SK hynix", name: "DDR5-6400 RDIMM", segment: "datacenter", year: 2024, usd: 0, usdPerGb: 6.4, memGen: "ddr5", memKind: "rdimm", caps: [32, 64, 96, 128, 256], kits: [1, 12, 24], mts: 6400, cl: 52, ecc: true, ranks: "2Rx4", volts: 1.1, heightMm: 31, registered: true, conditions: ["new"], highlights: ["Matches Turin's DDR5-6000 controller with headroom", "256GB modules for maximum density", "Registered, server boards only"], tags: ["ecc", "registered", "server", "fast"] },
  { key: "micron-ddr5-mrdimm-8800", brand: "Micron", name: "DDR5-8800 MRDIMM", segment: "datacenter", year: 2024, usd: 0, usdPerGb: 11, memGen: "ddr5", memKind: "mrdimm", caps: [32, 64, 96, 128], kits: [1, 8, 16], mts: 8800, cl: 62, ecc: true, ranks: "2Rx4", volts: 1.1, heightMm: 31, registered: true, conditions: ["new"], highlights: ["Multiplexed rank DIMM — two ranks answer at once, doubling peak bandwidth", "Only Xeon 6 supports it; it falls back to RDIMM speed elsewhere", "Expensive, and worth it only if you are memory bandwidth bound"], tags: ["ecc", "registered", "server", "bandwidth"] },
  { key: "samsung-ddr4-rdimm-2933", brand: "Samsung", name: "DDR4-2933 RDIMM", segment: "datacenter", year: 2019, usd: 0, usdPerGb: 1.3, memGen: "ddr4", memKind: "rdimm", caps: [16, 32, 64], kits: [1, 6, 12], mts: 2933, cl: 21, ecc: true, ranks: "2Rx4", volts: 1.2, heightMm: 31, registered: true, conditions: LEGACY, highlights: ["Cascade Lake native speed, six modules per socket", "The cheapest ECC per GB on the market", "Enormous supply from retired enterprise fleets"], tags: ["ecc", "registered", "server", "budget", "value"] },
  { key: "hynix-ddr4-rdimm-2400", brand: "SK hynix", name: "DDR4-2400 RDIMM", segment: "datacenter", year: 2016, usd: 0, usdPerGb: 0.8, memGen: "ddr4", memKind: "rdimm", caps: [16, 32], kits: [1, 4, 8], mts: 2400, cl: 17, ecc: true, ranks: "2Rx4", volts: 1.2, heightMm: 31, registered: true, conditions: ["refurb-a", "refurb-b", "pull"], highlights: ["Broadwell-EP era memory, almost free by the tray", "256GB on an E5 v4 board for a rounding error", "Slow, but ECC and abundant"], tags: ["ecc", "registered", "budget", "homelab"] },
  { key: "kingston-fury-ddr5-6000", brand: "Kingston", name: "FURY Beast DDR5-6000 CL36", segment: "desktop", year: 2023, usd: 0, usdPerGb: 3.0, memGen: "ddr5", memKind: "udimm", caps: [16, 32], kits: [2, 4], mts: 6000, cl: 36, ecc: false, ranks: "1Rx8", volts: 1.35, heightMm: 35, registered: false, conditions: ["new", "open-box"], highlights: ["35mm — clears most air towers, unlike taller RGB kits", "EXPO and XMP", "DDR5-6000 is the AM5 sweet spot"], tags: ["gaming", "expo", "value"] },
  { key: "corsair-ddr5-6400", brand: "Corsair", name: "Vengeance RGB DDR5-6400 CL32", segment: "desktop", year: 2023, usd: 0, usdPerGb: 3.9, memGen: "ddr5", memKind: "udimm", caps: [16, 24, 32, 48], kits: [2, 4], mts: 6400, cl: 32, ecc: false, ranks: "1Rx8", volts: 1.4, heightMm: 44, registered: false, conditions: ["new", "open-box"], highlights: ["44mm tall with the RGB diffuser — check cooler clearance", "Four-DIMM kits will not run at rated speed on most AM5 boards", "iCUE control"], tags: ["gaming", "rgb", "tall"] },
  { key: "kingston-ddr4-3200-udimm", brand: "Kingston", name: "FURY Beast DDR4-3200 CL16", segment: "desktop", year: 2020, usd: 0, usdPerGb: 1.6, memGen: "ddr4", memKind: "udimm", caps: [8, 16, 32], kits: [2, 4], mts: 3200, cl: 16, ecc: false, ranks: "1Rx8", volts: 1.35, heightMm: 34, registered: false, conditions: RETAIL, highlights: ["DDR4 is not dead — AM4 and LGA1700 both take it", "Half the price per GB of DDR5", "34mm, low enough for most coolers"], tags: ["gaming", "value", "budget"] },
  { key: "vcolor-ddr5-rdimm-ws", brand: "v-color", name: "DDR5-5600 ECC RDIMM Workstation", segment: "workstation", year: 2023, usd: 0, usdPerGb: 5.8, memGen: "ddr5", memKind: "rdimm", caps: [16, 32, 64, 96], kits: [4, 8], mts: 5600, cl: 46, ecc: true, ranks: "2Rx8", volts: 1.1, heightMm: 42, registered: true, conditions: ["new"], highlights: ["Overclocking-validated RDIMM for TRX50 and WRX90", "Heatspreaders, so 42mm tall", "8-module kits matched for 8-channel"], tags: ["ecc", "registered", "workstation", "matched"] },
];

/* =============================================================== Storage */

export const STORAGE_EXT: StorageFamily[] = [
  { key: "kioxia-cm7", brand: "KIOXIA", name: "CM7-R U.3 PCIe 5.0", segment: "datacenter", year: 2023, usd: 0, usdPerTb: 165, bus: "u3", caps: [1920, 3840, 7680, 15360, 30720], media: "nvme-tlc", readMbs: 14000, writeMbs: 6750, readIops: 2700000, writeIops: 310000, dwpd: 1, pcieGen: 5, pcieWidth: 4, physical: "2.5in-15mm", plp: true, tdpW: 25, conditions: ["new", "refurb-a"], highlights: ["14 GB/s on a single drive — PCIe 5.0 x4 saturated", "2.7M read IOPS", "Needs a Gen5 backplane to reach those numbers"], tags: ["nvme", "gen5", "plp", "hotswap", "fast"] },
  { key: "micron-9400", brand: "Micron", name: "9400 PRO U.3 NVMe", segment: "datacenter", year: 2023, usd: 0, usdPerTb: 118, bus: "u3", caps: [7680, 15360, 30720], media: "nvme-tlc", readMbs: 7000, writeMbs: 4500, readIops: 1600000, writeIops: 300000, dwpd: 1, pcieGen: 4, pcieWidth: 4, physical: "2.5in-15mm", plp: true, tdpW: 22, conditions: ["new", "refurb-a"], highlights: ["30.72TB in a 2.5in bay with real TLC endurance", "1.6M read IOPS", "PLP with full capacitor bank"], tags: ["nvme", "capacity", "plp", "hotswap"] },
  { key: "intel-p4610", brand: "Solidigm", name: "D7-P4610 U.2 NVMe", segment: "datacenter", year: 2018, usd: 0, usdPerTb: 55, bus: "u2", caps: [1600, 3200, 6400], media: "nvme-tlc", readMbs: 3200, writeMbs: 2080, readIops: 640000, writeIops: 200000, dwpd: 3, pcieGen: 3, pcieWidth: 4, physical: "2.5in-15mm", plp: true, tdpW: 14, conditions: LEGACY, highlights: ["3 DWPD — genuinely write-intensive endurance", "PCIe 3.0, so bandwidth is modest by modern standards", "Cheap, plentiful, and the endurance is usually barely touched"], tags: ["nvme", "plp", "endurance", "value", "budget"] },
  { key: "samsung-pm1743", brand: "Samsung", name: "PM1743 E3.S PCIe 5.0", segment: "datacenter", year: 2023, usd: 0, usdPerTb: 172, bus: "e3s", caps: [1920, 3840, 7680, 15360], media: "nvme-tlc", readMbs: 13000, writeMbs: 6600, readIops: 2500000, writeIops: 250000, dwpd: 1, pcieGen: 5, pcieWidth: 4, physical: "E3.S 7.5mm", plp: true, tdpW: 20, conditions: ["new"], highlights: ["E3.S form factor — the EDSFF replacement for U.2, not backwards compatible", "13 GB/s read", "Only fits chassis with an E3.S backplane"], tags: ["nvme", "gen5", "edsff", "fast"] },
  { key: "micron-7450-m2", brand: "Micron", name: "7450 PRO M.2 22110", segment: "datacenter", year: 2022, usd: 0, usdPerTb: 105, bus: "m2-nvme", caps: [480, 960, 1920, 3840], media: "nvme-tlc", readMbs: 5000, writeMbs: 2400, readIops: 800000, writeIops: 190000, dwpd: 1, pcieGen: 4, pcieWidth: 4, physical: "22110", plp: true, tdpW: 8, conditions: ["new", "refurb-a", "pull"], highlights: ["M.2 with power-loss protection, which is rare", "22110 length — will not fit a 2280-only slot", "The right boot drive for a server"], tags: ["nvme", "m2", "plp", "boot"] },
  { key: "samsung-990pro", brand: "Samsung", name: "990 PRO M.2 NVMe", segment: "desktop", year: 2022, usd: 0, usdPerTb: 82, bus: "m2-nvme", caps: [1000, 2000, 4000], media: "nvme-tlc", readMbs: 7450, writeMbs: 6900, readIops: 1400000, writeIops: 1550000, dwpd: 0.3, pcieGen: 4, pcieWidth: 4, physical: "2280", plp: false, tdpW: 8, conditions: ["new", "open-box"], highlights: ["The reference consumer NVMe drive", "No PLP — fine for a workstation, wrong for a database", "Update firmware on arrival"], tags: ["nvme", "m2", "desktop", "fast"] },
  { key: "crucial-p3plus", brand: "Crucial", name: "P3 Plus M.2 NVMe", segment: "desktop", year: 2022, usd: 0, usdPerTb: 48, bus: "m2-nvme", caps: [500, 1000, 2000, 4000], media: "nvme-qlc", readMbs: 5000, writeMbs: 4200, readIops: 650000, writeIops: 700000, dwpd: 0.1, pcieGen: 4, pcieWidth: 4, physical: "2280", plp: false, tdpW: 6, conditions: ["new", "open-box"], highlights: ["QLC — fast until the SLC cache fills, then it falls off a cliff", "Cheapest NVMe per TB", "Fine for a game library, wrong for a scratch disk"], tags: ["nvme", "m2", "qlc", "budget", "value"] },
  { key: "samsung-pm893", brand: "Samsung", name: "PM893 SATA SSD", segment: "datacenter", year: 2021, usd: 0, usdPerTb: 68, bus: "sata", caps: [480, 960, 1920, 3840, 7680], media: "sata-tlc", readMbs: 550, writeMbs: 520, readIops: 98000, writeIops: 30000, dwpd: 1, physical: "2.5in-7mm", plp: true, tdpW: 3, conditions: ["new", "refurb-a", "pull"], highlights: ["SATA is slow but the ports are already on your board", "PLP present, unlike consumer SATA drives", "Good boot and log tier"], tags: ["sata", "plp", "value", "boot"] },
  { key: "wd-red-pro", brand: "Western Digital", name: "Red Pro NAS HDD", segment: "workstation", year: 2022, usd: 0, usdPerTb: 24, bus: "sata", caps: [4000, 8000, 12000, 16000, 22000], media: "hdd-cmr", readMbs: 265, writeMbs: 265, readIops: 150, writeIops: 400, dwpd: 0, physical: "3.5in", plp: false, tdpW: 8, conditions: ["new", "refurb-a"], highlights: ["CMR throughout the range — no hidden SMR drives", "Rated for 24/7 in up to 24-bay enclosures", "550TB/yr workload rating"], tags: ["hdd", "cmr", "nas", "bulk"] },
  { key: "seagate-exos-x18-sata", brand: "Seagate", name: "Exos X18 SATA", segment: "datacenter", year: 2021, usd: 0, usdPerTb: 15, bus: "sata", caps: [10000, 12000, 14000, 16000, 18000], media: "hdd-cmr", readMbs: 270, writeMbs: 270, readIops: 170, writeIops: 440, dwpd: 0, physical: "3.5in", plp: false, tdpW: 9, conditions: LEGACY, highlights: ["Cheapest trustworthy bulk capacity in Pakistan", "Helium sealed, CMR", "Check power-on hours in SMART on any refurb"], tags: ["hdd", "cmr", "bulk", "value", "budget"] },
];

/* =================================================================== PSU */

export const PSUS_EXT: PsuFamily[] = [
  { key: "corsair-rmx", brand: "Corsair", name: "RMx Series Gold", segment: "desktop", year: 2024, usd: 0, usdPerKw: 145, watts: [750, 850, 1000, 1200], form: "atx", eff: "80+ gold", atx: "3.1", modular: "full", conn: { "12v2x6": 1, "pcie-8": 6, "eps-8": 2, "sata-power": 10 }, redundancy: 1, vMin: 100, derate230: 1.0, depthMm: 160, conditions: ["new", "open-box"], highlights: ["ATX 3.1 native 12V-2x6 at every wattage", "160mm, fits compact cases", "The default sensible choice"], tags: ["gold", "atx31", "value"] },
  { key: "seasonic-vertex-px", brand: "Seasonic", name: "VERTEX PX Platinum", segment: "workstation", year: 2023, usd: 0, usdPerKw: 220, watts: [850, 1000, 1200], form: "atx", eff: "80+ platinum", atx: "3.0", modular: "full", conn: { "12vhpwr": 1, "pcie-8": 6, "eps-8": 2, "sata-power": 12 }, redundancy: 1, vMin: 100, derate230: 1.0, depthMm: 170, conditions: ["new", "open-box", "refurb-a"], highlights: ["Platinum efficiency, 12-year warranty", "Handles a 5090 transient spike without tripping OCP", "170mm"], tags: ["platinum", "quiet", "reliable"] },
  { key: "beq-dark-power-13", brand: "be quiet!", name: "Dark Power 13 Titanium", segment: "workstation", year: 2023, usd: 0, usdPerKw: 300, watts: [850, 1000, 1300], form: "atx", eff: "80+ titanium", atx: "3.0", modular: "full", conn: { "12vhpwr": 1, "pcie-8": 6, "eps-8": 2, "sata-power": 10 }, redundancy: 1, vMin: 100, derate230: 1.0, depthMm: 200, conditions: ["new"], highlights: ["Quietest high-wattage unit made", "Switchable single/multi rail", "200mm deep — measure your PSU bay"], tags: ["titanium", "quiet"] },
  { key: "cooler-master-v-sfx", brand: "Cooler Master", name: "V SFX Platinum", segment: "desktop", year: 2023, usd: 0, usdPerKw: 260, watts: [850, 1100, 1300], form: "sfx", eff: "80+ platinum", atx: "3.1", modular: "full", conn: { "12v2x6": 1, "pcie-8": 4, "eps-8": 2, "sata-power": 6 }, redundancy: 1, vMin: 100, derate230: 1.0, depthMm: 100, conditions: ["new"], highlights: ["1300W in an SFX shell — enough for a 5090 in a small case", "Native 12V-2x6", "Loud under load; that is the price of the size"], tags: ["platinum", "sff", "atx31"] },
  { key: "evga-supernova-g", brand: "EVGA", name: "SuperNOVA G7 Gold", segment: "desktop", year: 2022, usd: 0, usdPerKw: 130, watts: [650, 750, 850, 1000], form: "atx", eff: "80+ gold", atx: "2.4", modular: "full", conn: { "pcie-8": 6, "eps-8": 2, "sata-power": 9 }, redundancy: 1, vMin: 100, derate230: 1.0, depthMm: 150, conditions: LEGACY, highlights: ["No 12VHPWR — you will need an adapter for a modern card, which is a compromise", "Fine for 30-series and Radeon builds", "150mm, very compact"], tags: ["gold", "value", "budget", "legacy"] },
  { key: "smc-crps-1u", brand: "Supermicro", name: "CRPS 1U Redundant", segment: "datacenter", year: 2021, usd: 0, usdPerKw: 280, watts: [750, 1000, 1200, 1600], form: "redundant-1u", eff: "80+ platinum", atx: "2.4", modular: "none", conn: {}, redundancy: 2, vMin: 100, derate230: 1.0, depthMm: 185, conditions: SERVER, highlights: ["1+1 hot-swap in 1U", "Fits Supermicro and most CRPS-standard chassis", "Loud — these are 40mm fans at full tilt"], tags: ["redundant", "hotswap", "rack", "1u"] },
  { key: "delta-crps-3000", brand: "Delta", name: "CRPS 3000W Titanium", segment: "datacenter", year: 2023, usd: 0, usdPerKw: 290, watts: [2000, 2400, 3000], form: "crps", eff: "80+ titanium", atx: "2.4", modular: "none", conn: {}, redundancy: 2, vMin: 200, derate230: 1.0, depthMm: 265, conditions: ["new", "refurb-a"], highlights: ["200-240V input only — perfect for Pakistan, useless on a 110V bench", "Titanium at full load", "The module behind most 8-GPU nodes"], tags: ["redundant", "rack", "titanium", "high-power"] },
];

/* =============================================================== Cooling */

export const COOLERS_EXT: CoolerFamily[] = [
  { key: "nh-u12a", brand: "Noctua", name: "NH-U12A chromax.black", segment: "desktop", year: 2022, usd: 120, type: "air-tower", sockets: ["AM5", "AM4", "LGA1700", "LGA1851"], tdpW: 220, heightMm: 158, radMm: 0, needsAirflow: false, dba: 22, conditions: ["new", "open-box"], highlights: ["120mm tower that matches most 140mm coolers", "158mm — fits far more cases than a D15", "Clears tall RAM"], tags: ["air", "quiet", "compact"] },
  { key: "nh-l9a", brand: "Noctua", name: "NH-L9a-AM5", segment: "desktop", year: 2022, usd: 55, type: "air-low", sockets: ["AM5", "AM4"], tdpW: 95, heightMm: 37, radMm: 0, needsAirflow: false, dba: 23, conditions: ["new"], highlights: ["37mm tall — for genuinely tiny builds", "95W ceiling, so pair it with a 65W chip", "Does not overhang the RAM slots"], tags: ["air", "low-profile", "sff"] },
  { key: "ak620", brand: "DeepCool", name: "AK620 Digital", segment: "desktop", year: 2023, usd: 65, type: "air-tower", sockets: ["AM5", "AM4", "LGA1700", "LGA1851"], tdpW: 260, heightMm: 160, radMm: 0, needsAirflow: false, dba: 28, conditions: ["new", "open-box"], highlights: ["Dual tower for a third of Noctua money", "260W rating handles a 14700K", "160mm"], tags: ["air", "value", "tall"] },
  { key: "arctic-lf3-360", brand: "Arctic", name: "Liquid Freezer III 360", segment: "desktop", year: 2024, usd: 90, type: "aio", sockets: ["AM5", "AM4", "LGA1700", "LGA1851"], tdpW: 300, heightMm: 0, radMm: 360, needsAirflow: false, dba: 26, conditions: ["new", "open-box"], highlights: ["360mm fits far more cases than the 420", "VRM fan on the block", "Best cooling per rupee"], tags: ["aio", "liquid", "value"] },
  { key: "sp3-4u-tower", brand: "Dynatron", name: "A26 4U SP5 Active", segment: "datacenter", year: 2023, usd: 95, type: "air-tower", sockets: ["SP5"], tdpW: 400, heightMm: 105, radMm: 0, needsAirflow: false, dba: 42, conditions: ["new"], highlights: ["Self-contained fan, so it works in a tower as well as a 4U", "400W rating covers a 9654", "105mm"], tags: ["air", "rack", "4u", "epyc"] },
  { key: "dynatron-l31", brand: "Dynatron", name: "L31 1U SP5 Liquid", segment: "datacenter", year: 2023, usd: 260, type: "aio", sockets: ["SP5"], tdpW: 400, heightMm: 26, radMm: 120, needsAirflow: true, dba: 50, conditions: ["new"], highlights: ["Closed-loop liquid in 1U — the only way to run a 400W EPYC that thin", "Radiator sits in the chassis airflow path", "Self-contained, no facility water"], tags: ["liquid", "rack", "1u", "epyc"] },
  { key: "smc-snk-p0083ap4", brand: "Supermicro", name: "SNK-P0083AP4 4U Active", segment: "datacenter", year: 2022, usd: 68, type: "air-tower", sockets: ["LGA4677"], tdpW: 350, heightMm: 105, radMm: 0, needsAirflow: false, dba: 40, conditions: ["new", "pull"], highlights: ["Active 4U heatsink for Sapphire Rapids", "350W rating", "Works outside a chassis, unlike the passive versions"], tags: ["air", "rack", "4u", "xeon"] },
  { key: "tr-aio-360", brand: "SilverStone", name: "XE360-TR5 Threadripper AIO", segment: "workstation", year: 2023, usd: 210, type: "aio", sockets: ["sTR5", "sWRX8"], tdpW: 420, heightMm: 0, radMm: 360, needsAirflow: false, dba: 30, conditions: ["new"], highlights: ["Full sTR5 IHS coverage — most AIOs only touch the middle", "420W rating for the 350W parts", "Copper cold plate sized for the socket"], tags: ["aio", "liquid", "threadripper", "workstation"] },
  { key: "arctic-mx6", brand: "Arctic", name: "MX-6 Thermal Compound 8g", segment: "desktop", year: 2022, usd: 9, type: "air-low", sockets: ["Universal"], tdpW: 0, heightMm: 0, radMm: 0, needsAirflow: false, dba: 0, conditions: ["new"], highlights: ["Non-conductive, 8 grams covers a dozen desktop dies or two SP5 lids", "Re-paste every refurbished CPU you receive", "No cure time"], tags: ["consumable", "paste"] },
];

/* =============================================================== Chassis */

export const CHASSIS_EXT: ChassisFamily[] = [
  { key: "smc-cse-847", brand: "Supermicro", name: "CSE-847 4U 36-Bay", segment: "datacenter", year: 2019, usd: 1100, form: "4u", rackU: 4, moboForms: ["eatx", "ssi-eeb", "atx"], psuForms: ["redundant-2u", "crps"], maxGpuMm: 267, maxCoolerMm: 80, maxRadMm: 0, slots: 7, bays35: 36, bays25: 0, hotSwap: 36, backplane: "sas3", airflow: true, maxGpus: 2, depthMm: 673, kg: 32, conditions: LEGACY, highlights: ["36 hot-swap 3.5in bays — 24 front, 12 rear", "The classic bulk storage chassis", "Two GPUs at most; this is a JBOD host, not a compute node"], tags: ["rack", "4u", "storage", "hotswap", "bulk"] },
  { key: "smc-cse-216", brand: "Supermicro", name: "CSE-216 2U 24-Bay NVMe", segment: "datacenter", year: 2021, usd: 1400, form: "2u", rackU: 2, moboForms: ["eatx", "proprietary"], psuForms: ["crps", "redundant-2u"], maxGpuMm: 267, maxCoolerMm: 80, maxRadMm: 0, slots: 6, bays35: 0, bays25: 24, hotSwap: 24, backplane: "u2", airflow: true, maxGpus: 2, depthMm: 650, kg: 24, conditions: SERVER, highlights: ["24 U.2 NVMe bays in 2U", "Direct-attach backplane, no expander latency", "Two low-profile GPUs maximum"], tags: ["rack", "2u", "nvme", "hotswap", "storage"] },
  { key: "smc-cse-829", brand: "Supermicro", name: "CSE-829 2U GPU", segment: "datacenter", year: 2022, usd: 1600, form: "2u", rackU: 2, moboForms: ["eatx", "proprietary"], psuForms: ["redundant-2u"], maxGpuMm: 268, maxCoolerMm: 60, maxRadMm: 0, slots: 6, bays35: 8, bays25: 0, hotSwap: 8, backplane: "sas3", airflow: true, maxGpus: 4, depthMm: 700, kg: 26, conditions: SERVER, highlights: ["Four double-width passive GPUs in 2U", "Very high static pressure fans — this is a loud machine", "60mm CPU cooler ceiling"], tags: ["rack", "2u", "gpu-dense", "loud"] },
  { key: "gb-g593", brand: "GIGABYTE", name: "G593-SD0 5U HGX", segment: "datacenter", year: 2023, usd: 18000, form: "5u", rackU: 5, moboForms: ["proprietary"], psuForms: ["redundant-2u"], maxGpuMm: 0, maxCoolerMm: 80, maxRadMm: 0, slots: 12, bays35: 0, bays25: 8, hotSwap: 8, backplane: "u2", airflow: true, maxGpus: 8, depthMm: 900, kg: 90, conditions: ["new"], highlights: ["Purpose-built for an HGX H100/H200 8-GPU baseboard", "Takes 3000W+ redundant modules", "900mm deep — will not fit a 1000mm rack with cabling"], tags: ["rack", "5u", "hgx", "gpu-dense", "flagship"] },
  { key: "fractal-torrent", brand: "Fractal Design", name: "Torrent", segment: "desktop", year: 2021, usd: 200, form: "full-tower", rackU: 0, moboForms: ["atx", "matx", "itx", "eatx", "ssi-eeb"], psuForms: ["atx", "sfx"], maxGpuMm: 461, maxCoolerMm: 188, maxRadMm: 420, slots: 7, bays35: 4, bays25: 4, hotSwap: 0, backplane: "none", airflow: true, maxGpus: 3, depthMm: 544, kg: 12, conditions: ["new", "open-box"], highlights: ["Two 180mm front fans — the best airflow case made", "The right choice for a multi-GPU air-cooled build", "461mm GPU clearance"], tags: ["tower", "airflow", "eatx", "multi-gpu"] },
  { key: "lianli-o11d-evo", brand: "Lian Li", name: "O11 Dynamic EVO XL", segment: "desktop", year: 2023, usd: 220, form: "full-tower", rackU: 0, moboForms: ["atx", "matx", "itx", "eatx"], psuForms: ["atx", "sfx"], maxGpuMm: 460, maxCoolerMm: 167, maxRadMm: 420, slots: 8, bays35: 4, bays25: 6, hotSwap: 0, backplane: "none", airflow: false, maxGpus: 2, depthMm: 520, kg: 15, conditions: ["new", "open-box"], highlights: ["Takes three 360mm radiators", "Glass on two sides, so plan for the heat", "Reversible layout"], tags: ["tower", "watercooling", "showcase"] },
  { key: "cm-nr200", brand: "Cooler Master", name: "NR200P MAX", segment: "desktop", year: 2022, usd: 350, form: "mid-tower", rackU: 0, moboForms: ["itx"], psuForms: ["sfx", "sfx-l"], maxGpuMm: 336, maxCoolerMm: 67, maxRadMm: 280, slots: 3, bays35: 1, bays25: 2, hotSwap: 0, backplane: "none", airflow: false, maxGpus: 1, depthMm: 376, kg: 7, conditions: ["new"], highlights: ["18 litres, takes a 336mm GPU", "Ships with an 850W SFX unit and a 280mm AIO", "ITX only"], tags: ["sff", "itx", "compact"] },
  { key: "sm-4u-gpu-8", brand: "AIC", name: "SB402-LX 4U 8-GPU", segment: "datacenter", year: 2022, usd: 2100, form: "4u", rackU: 4, moboForms: ["eatx", "ssi-eeb"], psuForms: ["redundant-2u"], maxGpuMm: 330, maxCoolerMm: 85, maxRadMm: 0, slots: 11, bays35: 0, bays25: 8, hotSwap: 8, backplane: "u2", airflow: true, maxGpus: 8, depthMm: 780, kg: 35, conditions: ["new", "refurb-a"], highlights: ["Eight double-width slots on a standard E-ATX board", "Takes commodity motherboards, unlike the vendor HGX chassis", "780mm deep"], tags: ["rack", "4u", "gpu-dense", "hotswap"] },
  { key: "mining-frame-8", brand: "Veddha", name: "V3C 8-GPU Open Frame", segment: "edge", year: 2021, usd: 130, form: "open-frame", rackU: 0, moboForms: ["atx", "matx"], psuForms: ["atx"], maxGpuMm: 340, maxCoolerMm: 160, maxRadMm: 0, slots: 8, bays35: 1, bays25: 2, hotSwap: 0, backplane: "none", airflow: false, maxGpus: 8, depthMm: 600, kg: 6, conditions: ["new", "open-box"], highlights: ["Eight GPUs on risers, stackable frames", "Aluminium, tool-free assembly", "No dust filtering at all"], tags: ["open-frame", "gpu-dense", "rig", "value"] },
];

/* ================================================================ Fabric */

export const NICS_EXT: NicFamily[] = [
  { key: "cx6-dx-100", brand: "NVIDIA", name: "ConnectX-6 Dx 100GbE", segment: "datacenter", year: 2020, usd: 1100, fabric: "ethernet", gbps: 100, ports: 2, portType: "qsfp56", pcieGen: 4, pcieWidth: 16, tdpW: 22, rdma: true, sriov: true, gpuDirect: true, lowProfile: false, conditions: SERVER, highlights: ["Dual 100GbE with hardware crypto offload", "RoCEv2 and GPUDirect", "Ethernet only, no InfiniBand mode"], tags: ["ethernet", "100g", "roce", "gpudirect"] },
  { key: "cx4-lx-25", brand: "NVIDIA", name: "ConnectX-4 Lx 25GbE", segment: "datacenter", year: 2016, usd: 95, fabric: "ethernet", gbps: 25, ports: 2, portType: "sfp28", pcieGen: 3, pcieWidth: 8, tdpW: 11, rdma: true, sriov: true, gpuDirect: false, lowProfile: true, conditions: LEGACY, highlights: ["Dual 25G for less than a decent SATA SSD", "RoCE capable", "The cheapest real upgrade over 10G"], tags: ["ethernet", "25g", "value", "budget", "low-profile"] },
  { key: "bcm-57414", brand: "Broadcom", name: "BCM57414 25GbE", segment: "datacenter", year: 2018, usd: 170, fabric: "ethernet", gbps: 25, ports: 2, portType: "sfp28", pcieGen: 3, pcieWidth: 8, tdpW: 13, rdma: true, sriov: true, gpuDirect: false, lowProfile: true, conditions: LEGACY, highlights: ["Very common in Dell and HPE pulls", "RoCEv2", "Accepts third-party optics more readily than Intel"], tags: ["ethernet", "25g", "value", "low-profile"] },
  { key: "intel-x520", brand: "Intel", name: "X520-DA2 10GbE", segment: "datacenter", year: 2010, usd: 45, fabric: "ethernet", gbps: 10, ports: 2, portType: "sfp+", pcieGen: 2, pcieWidth: 8, tdpW: 6, rdma: false, sriov: true, gpuDirect: false, lowProfile: true, conditions: ["refurb-a", "refurb-b", "pull"], highlights: ["Ancient, ubiquitous, and works with every OS ever written", "Locks out non-Intel optics unless you patch the driver", "The cheapest 10G there is"], tags: ["ethernet", "10g", "budget", "legacy", "low-profile"] },
  { key: "cx7-400-eth", brand: "NVIDIA", name: "ConnectX-7 400GbE QSFP112", segment: "datacenter", year: 2022, usd: 2200, fabric: "ethernet", gbps: 400, ports: 1, portType: "qsfp-dd", pcieGen: 5, pcieWidth: 16, tdpW: 25, rdma: true, sriov: true, gpuDirect: true, lowProfile: false, conditions: ["new", "refurb-a"], highlights: ["400GbE with GPUDirect for Ethernet-scaled training", "Requires PCIe 5.0 x16 to reach line rate", "The alternative to InfiniBand for large clusters"], tags: ["ethernet", "400g", "gpudirect", "roce"] },
  { key: "cx6-ib-only", brand: "NVIDIA", name: "ConnectX-6 HDR100 InfiniBand-only", segment: "datacenter", year: 2020, usd: 640, fabric: "infiniband", gbps: 100, ports: 1, portType: "qsfp56", pcieGen: 4, pcieWidth: 16, tdpW: 18, rdma: true, sriov: true, gpuDirect: true, lowProfile: true, conditions: SERVER, highlights: ["InfiniBand-only part number — it has no Ethernet personality at all", "Cheaper than the VPI equivalent if you are certain you want IB", "Check the SKU carefully: the VPI and IB-only cards look identical"], tags: ["infiniband", "100g", "rdma", "gpudirect", "low-profile"] },
  { key: "cx3-vpi-fdr", brand: "NVIDIA", name: "ConnectX-3 VPI FDR56", segment: "datacenter", year: 2013, usd: 55, fabric: "both", gbps: 56, ports: 2, portType: "qsfp+", pcieGen: 3, pcieWidth: 8, tdpW: 9, rdma: true, sriov: true, gpuDirect: false, lowProfile: true, conditions: ["refurb-a", "refurb-b", "pull"], highlights: ["56Gb RDMA for pocket money", "Dropped from recent MLNX_OFED releases — you will be on an older driver stack", "The cheapest way to learn InfiniBand"], tags: ["infiniband", "56g", "rdma", "budget", "homelab", "legacy", "low-profile"] },
  { key: "lsi-9400-16i", brand: "Broadcom", name: "HBA 9400-16i Tri-Mode", segment: "datacenter", year: 2018, usd: 320, fabric: "ethernet", gbps: 0, ports: 16, portType: "rj45", pcieGen: 3, pcieWidth: 8, tdpW: 14, rdma: false, sriov: false, gpuDirect: false, lowProfile: true, conditions: SERVER, highlights: ["Tri-mode: SAS, SATA and NVMe on the same connector", "IT mode firmware for ZFS — flash it before use", "16 internal ports via four SFF-8643"], tags: ["hba", "sas", "zfs", "storage"] },
];

export const SWITCHES_EXT: SwitchFamily[] = [
  { key: "sn3700", brand: "NVIDIA", name: "Spectrum-2 SN3700 200GbE", segment: "datacenter", year: 2020, usd: 16000, fabric: "ethernet", ports: 32, gbps: 200, portType: "qsfp56", rackU: 1, tbps: 12.8, tdpW: 500, managed: true, airflow: "reversible", psuRedundant: true, conditions: ["new", "refurb-a"], highlights: ["32x 200GbE, 12.8 Tb/s in 1U", "Cumulus Linux or SONiC", "Deep buffers for lossless RoCE"], tags: ["ethernet", "200g", "spine", "roce"] },
  { key: "sx6036", brand: "NVIDIA", name: "SwitchX-2 SX6036 FDR", segment: "datacenter", year: 2013, usd: 900, fabric: "infiniband", ports: 36, gbps: 56, portType: "qsfp+", rackU: 1, tbps: 4, tdpW: 230, managed: true, airflow: "reversible", psuRedundant: true, conditions: ["refurb-a", "refurb-b", "pull"], highlights: ["36 ports of FDR56 InfiniBand for the price of a GPU", "Old, but RDMA is RDMA — excellent for learning", "Subnet manager runs onboard"], tags: ["infiniband", "56g", "budget", "legacy", "homelab"] },
  { key: "cisco-n9k-93180", brand: "Cisco", name: "Nexus 93180YC-EX", segment: "datacenter", year: 2016, usd: 3200, fabric: "ethernet", ports: 48, gbps: 25, portType: "sfp28", rackU: 1, tbps: 3.6, tdpW: 300, managed: true, airflow: "reversible", psuRedundant: true, conditions: LEGACY, highlights: ["48x 25G plus 6x 100G uplinks", "NX-OS — a known quantity for most Pakistani network teams", "Very cheap used"], tags: ["ethernet", "25g", "leaf", "value"] },
  { key: "mikrotik-crs326", brand: "MikroTik", name: "CRS326-24S+2Q+RM 10G", segment: "edge", year: 2020, usd: 400, fabric: "ethernet", ports: 24, gbps: 10, portType: "sfp+", rackU: 1, tbps: 0.4, tdpW: 40, managed: true, airflow: "reversible", psuRedundant: false, conditions: ["new", "open-box"], highlights: ["24x 10G plus 2x 40G at a fraction of enterprise cost", "Silent with the fans swapped", "RouterOS or SwitchOS"], tags: ["ethernet", "10g", "budget", "value", "edge"] },
];

export const OPTICS_EXT: OpticFamily[] = [
  { key: "dac-400g", brand: "FS", name: "400G OSFP Passive DAC", segment: "datacenter", year: 2023, usd: 280, media: "dac-passive", portType: "osfp", gbps: 400, lengths: [0.5, 1, 1.5, 2, 3], reachM: 3, codedFor: ["NVIDIA/Mellanox", "Generic"], fabric: "both", powerW: 0, conditions: ["new"], highlights: ["NDR InfiniBand or 400GbE in-rack", "Thick and stiff — plan the cable routing before you order", "3m maximum at this speed"], tags: ["dac", "400g", "in-rack", "infiniband"] },
  { key: "aoc-100g", brand: "FS", name: "100G QSFP28 AOC", segment: "datacenter", year: 2020, usd: 130, media: "aoc", portType: "qsfp28", gbps: 100, lengths: [3, 5, 10, 15, 30, 50], reachM: 50, codedFor: ["NVIDIA/Mellanox", "Cisco", "Arista", "Generic"], fabric: "ethernet", powerW: 3.5, conditions: ["new"], highlights: ["Flexible, thin, and pre-terminated", "50m reach for cross-row links", "Cheaper than two SR4 modules plus fibre under 30m"], tags: ["aoc", "100g", "cross-rack"] },
  { key: "lr4-100g", brand: "FS", name: "100G QSFP28 LR4 SMF", segment: "datacenter", year: 2020, usd: 480, media: "lr", portType: "qsfp28", gbps: 100, lengths: [0], reachM: 10000, codedFor: ["NVIDIA/Mellanox", "Cisco", "Arista", "Juniper", "Generic"], fabric: "ethernet", powerW: 4.5, conditions: ["new", "refurb-a"], highlights: ["10km over single-mode duplex LC", "For linking buildings, not racks", "4.5W per module"], tags: ["optic", "100g", "singlemode", "long-reach"] },
  { key: "sr-10g", brand: "FS", name: "10G SFP+ SR MMF", segment: "datacenter", year: 2018, usd: 18, media: "sr", portType: "sfp+", gbps: 10, lengths: [0], reachM: 300, codedFor: ["NVIDIA/Mellanox", "Cisco", "Intel", "Arista", "Juniper", "Generic", "Ubiquiti"], fabric: "ethernet", powerW: 1, conditions: ["new"], highlights: ["300m over OM4", "The commodity 10G optic", "Intel-coded version needed for X520/X710 unless the port is unlocked"], tags: ["optic", "10g", "multimode", "value"] },
  { key: "dac-40g", brand: "FS", name: "40G QSFP+ Passive DAC", segment: "datacenter", year: 2016, usd: 32, media: "dac-passive", portType: "qsfp+", gbps: 40, lengths: [1, 2, 3, 5, 7], reachM: 7, codedFor: ["NVIDIA/Mellanox", "Cisco", "Arista", "Generic"], fabric: "both", powerW: 0, conditions: ["new"], highlights: ["40G copper, or 4x10G with a breakout", "7m reach — copper carries further at lower speeds", "Very cheap"], tags: ["dac", "40g", "in-rack", "budget"] },
];

/* ==================================================== Facility + systems */

export const RACKS_EXT: RackFamily[] = [
  { key: "apc-nk-48u", brand: "APC", name: "NetShelter SX 48U Deep", segment: "datacenter", year: 2021, usd: 2400, heightU: 48, widthMm: 750, depthMm: 1200, loadKg: 1364, perfPct: 80, pduSlots: 6, shielded: false, conditions: ["new", "refurb-a"], highlights: ["1200mm deep — takes a 900mm HGX chassis with cabling behind it", "48U in a standard-height room", "80% perforation"], tags: ["48u", "deep", "wide", "gpu-ready"] },
  { key: "toten-42u", brand: "Toten", name: "G3 42U Server Rack", segment: "datacenter", year: 2022, usd: 750, heightU: 42, widthMm: 600, depthMm: 1000, loadKg: 800, perfPct: 70, pduSlots: 2, shielded: false, conditions: ["new"], highlights: ["The value 42U — widely stocked in Karachi and Lahore", "1000mm depth handles most 4U servers", "800kg static load, so do not fill it with storage chassis"], tags: ["42u", "value", "budget"] },
  { key: "wall-9u", brand: "Toten", name: "9U Wall Mount", segment: "edge", year: 2021, usd: 140, heightU: 9, widthMm: 600, depthMm: 450, loadKg: 60, perfPct: 55, pduSlots: 1, shielded: false, conditions: ["new"], highlights: ["Branch office or lab switch cabinet", "450mm deep — switches and patch panels only", "Glass door"], tags: ["9u", "wall", "edge", "budget"] },
];

export const PDUS_EXT: PduFamily[] = [
  { key: "apc-ap7921", brand: "APC", name: "AP7921B Switched PDU 1U", segment: "datacenter", year: 2019, usd: 650, outlets: 8, outletType: "C13", phases: 1, amps: 16, kw: 3.7, metered: true, switched: true, rackU: 1, volts: 230, conditions: SERVER, highlights: ["Remote power cycling — worth it the first time a node hangs at 3am", "8x C13, 3.7kW", "1U horizontal"], tags: ["switched", "metered", "230v", "1u"] },
  { key: "vertiv-vp8861", brand: "Vertiv", name: "Geist VP8861 Metered PDU", segment: "datacenter", year: 2021, usd: 900, outlets: 24, outletType: "C13/C19", phases: 1, amps: 32, kw: 7.4, metered: true, switched: false, rackU: 0, volts: 230, conditions: ["new", "refurb-a"], highlights: ["Per-outlet current metering without the switching premium", "7.4kW at 230V", "Zero-U, tool-free mounting"], tags: ["metered", "230v", "zero-u", "value"] },
  { key: "toten-pdu-16", brand: "Toten", name: "1U PDU 16-Way C13", segment: "edge", year: 2022, usd: 95, outlets: 16, outletType: "C13", phases: 1, amps: 16, kw: 3.6, metered: false, switched: false, rackU: 1, volts: 230, conditions: ["new"], highlights: ["Sixteen C13 outlets, unmetered", "3.6kW", "Cheap and it works"], tags: ["basic", "230v", "value", "budget"] },
];

export const UPSES_EXT: UpsFamily[] = [
  { key: "apc-srt5k", brand: "APC", name: "Smart-UPS SRT 5kVA", segment: "datacenter", year: 2019, usd: 4100, va: 5000, watts: 4500, topology: "online-double-conversion", rackU: 3, runtimeMin: 9, extBattery: true, outlets: 10, volts: 230, conditions: SERVER, highlights: ["Online double conversion in 3U", "4500W covers a single GPU node", "Takes external battery packs for longer holdover"], tags: ["online", "rack", "230v"] },
  { key: "apc-bx2200", brand: "APC", name: "Back-UPS BX2200MI", segment: "workstation", year: 2021, usd: 300, va: 2200, watts: 1200, topology: "line-interactive", rackU: 0, runtimeMin: 6, extBattery: false, outlets: 6, volts: 230, conditions: ["new", "open-box"], highlights: ["Tower unit for a workstation", "1200W — will not hold a dual-GPU rig, size it honestly", "Simulated sine wave; some PSUs dislike it"], tags: ["line-interactive", "tower", "230v", "budget"] },
  { key: "vertiv-gxt5-10k", brand: "Vertiv", name: "Liebert GXT5 10kVA", segment: "datacenter", year: 2021, usd: 6900, va: 10000, watts: 10000, topology: "online-double-conversion", rackU: 6, runtimeMin: 6, extBattery: true, outlets: 12, volts: 230, conditions: ["new", "refurb-a"], highlights: ["Unity power factor — 10kVA is a genuine 10kW", "Handles generator changeover cleanly", "Hardwired input"], tags: ["online", "rack", "230v", "generator", "high-power"] },
];

export const SYSTEMS_EXT: SystemFamily[] = [
  { key: "sys-2xa6000-ws", brand: "SUPERCOMPUTERS", name: "TF-W2P Pro Workstation", segment: "workstation", year: 2024, usd: 13500, category: "ai-workstation", rackU: 0, nodes: 1, cpuModel: "AMD Threadripper PRO 7965WX", cpuSockets: 1, coresTotal: 24, gpuModel: "NVIDIA RTX A6000 48GB", gpuCount: 2, memGb: 256, memGen: "ddr5", storage: "2x 2TB M.2 NVMe + 1x 7.68TB U.2", fabric: "2x 10GbE onboard", peakW: 1250, bf16: 310, stack: ["Ubuntu 24.04 LTS", "CUDA 12", "PyTorch 2", "Docker", "JupyterLab"], burnIn: 24, conditions: ["new", "refurb-a"], highlights: ["96GB of ECC VRAM across an NVLink pair", "Runs on a single 230V wall socket", "The workstation most Pakistani research groups actually need"], tags: ["workstation", "ecc", "nvlink", "desk-side", "value"] },
  { key: "sys-4x4090-rig", brand: "SUPERCOMPUTERS", name: "TF-R4 Open Frame Rig", segment: "edge", year: 2024, usd: 9500, category: "ai-rig", rackU: 0, nodes: 1, cpuModel: "AMD Ryzen Threadripper PRO 5975WX", cpuSockets: 1, coresTotal: 32, gpuModel: "NVIDIA GeForce RTX 4090 24GB", gpuCount: 4, memGb: 256, memGen: "ddr4", storage: "2x 4TB M.2 NVMe", fabric: "1x 10GbE", peakW: 2400, bf16: 660, stack: ["Ubuntu 24.04 LTS", "CUDA 12", "vLLM", "Ollama"], burnIn: 24, conditions: ["new", "refurb-a"], highlights: ["96GB VRAM on an open frame with real spacing between cards", "2400W — needs two circuits or a dedicated 20A feed", "No ECC and no NVLink; the economics make up for it"], tags: ["rig", "open-frame", "local-llm", "value", "high-power"] },
  { key: "sys-vdi-node", brand: "SUPERCOMPUTERS", name: "TF-V2 VDI Node", segment: "datacenter", year: 2024, usd: 32000, category: "gpu-server", rackU: 2, nodes: 1, cpuModel: "2x Intel Xeon Gold 6548Y+", cpuSockets: 2, coresTotal: 64, gpuModel: "NVIDIA L40 48GB", gpuCount: 4, memGb: 1024, memGen: "ddr5", storage: "8x 3.84TB U.2 NVMe", fabric: "2x 25GbE", peakW: 2400, bf16: 724, stack: ["VMware ESXi or Proxmox", "NVIDIA vGPU host driver", "Horizon or Omnissa"], burnIn: 48, conditions: ["new", "refurb-a"], highlights: ["Up to 64 virtual workstations on four L40s", "vGPU licensing quoted separately — it is per-user and annual", "Designed for engineering firms consolidating CAD seats"], tags: ["vdi", "vgpu", "gpu-dense", "virtualisation"] },
  { key: "sys-cluster-8", brand: "SUPERCOMPUTERS", name: "TF-C8 Starter Cluster", segment: "datacenter", year: 2024, usd: 78000, category: "cluster", rackU: 16, nodes: 8, cpuModel: "2x AMD EPYC 9354 per node", cpuSockets: 16, coresTotal: 512, gpuModel: null, gpuCount: 0, memGb: 4096, memGen: "ddr5", storage: "8x 3.84TB U.2 + 100TB shared", fabric: "HDR200 InfiniBand, QM8700 spine", peakW: 9600, bf16: 0, stack: ["Rocky Linux 9", "Slurm", "OpenMPI", "Warewulf", "Open OnDemand"], burnIn: 96, conditions: ["new", "refurb-a"], highlights: ["512 cores across eight nodes in one rack", "Open OnDemand gives researchers a browser interface instead of ssh", "Sized for a university department, not a national facility"], tags: ["cluster", "hpc", "infiniband", "university", "turnkey"] },
  { key: "sys-1u-inference", brand: "SUPERCOMPUTERS", name: "TF-L8 Edge Inference", segment: "edge", year: 2024, usd: 21000, category: "gpu-server", rackU: 1, nodes: 1, cpuModel: "AMD EPYC 9124", cpuSockets: 1, coresTotal: 16, gpuModel: "NVIDIA L4 24GB", gpuCount: 8, memGb: 256, memGen: "ddr5", storage: "4x 1.92TB U.2 NVMe", fabric: "2x 25GbE", peakW: 900, bf16: 968, stack: ["Ubuntu 22.04 LTS", "Triton Inference Server", "TensorRT", "Prometheus"], burnIn: 48, conditions: ["new"], highlights: ["Eight L4s in 1U on 900W total", "No auxiliary GPU power cables anywhere in the box", "Fits a colocation cabinet with a normal power allocation"], tags: ["1u", "edge", "inference", "efficient", "gpu-dense"] },
];
