"use client";

import { BRAND } from "@/lib/brand";
import { CONDITION_LABEL, KIND_LABEL, type Kind, type Product } from "@/lib/catalog";
import type { BuildSummary, Finding, Target } from "@/lib/compat/types";
import { TARGET_LABEL } from "@/lib/compat/types";

/**
 * The printable requirement document.
 *
 * This is the artefact that leaves the site: the customer prints it to PDF and
 * it reaches us as the record of what they asked for. It is rendered in the
 * normal page flow (hidden on screen, shown at print) rather than generated by
 * a PDF library, the browser's own print engine gives better typography than
 * jsPDF at zero bytes of JavaScript, and the layout stays in one place.
 *
 * `print.css` handles the A4 page box and forces an ink-friendly palette; this
 * component only owns the content and its order.
 */

export interface QuoteMeta {
  name: string;
  org: string;
  email: string;
  phone: string;
  city: string;
  timeline: string;
  workloads: string[];
  notes: string;
}

interface Props {
  ref_: string;
  meta: QuoteMeta;
  lines: Array<{ product: Product; qty: number }>;
  summary: BuildSummary;
  findings: Finding[];
  target: Target;
}

const ORDER: Kind[] = [
  "system", "chassis", "motherboard", "cpu", "cooler", "memory",
  "gpu", "storage", "psu", "nic", "switch", "optic", "rack", "pdu", "ups",
];

export default function QuoteDocument({ ref_, meta, lines, summary, findings, target }: Props) {
  const grouped = ORDER.map((k) => ({
    kind: k,
    items: lines.filter((l) => l.product.kind === k),
  })).filter((g) => g.items.length > 0);

  const blocking = findings.filter((f) => f.severity === "error");
  const warnings = findings.filter((f) => f.severity === "warn");
  const totalUnits = lines.reduce((n, l) => n + l.qty, 0);
  const today = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

  return (
    <article id="quote-doc" className="quote-doc" aria-label="Printable requirement document">
      {/* ------------------------------------------------------------ head */}
      <header className="qd-head">
        <div>
          <h1 className="qd-brand">{BRAND.name}</h1>
          <p className="qd-sub">{BRAND.legal}</p>
        </div>
        <div className="qd-meta">
          <p><strong>Requirement</strong> {ref_}</p>
          <p>{today}</p>
          <p>{BRAND.email}</p>
          <p>{BRAND.phone}</p>
        </div>
      </header>

      <h2 className="qd-title">Request for quotation</h2>

      {/* --------------------------------------------------------- customer */}
      <section className="qd-section">
        <h3 className="qd-h3">Requested by</h3>
        <table className="qd-kv">
          <tbody>
            {([
              ["Name", meta.name || "Not given"],
              ["Organisation", meta.org || "Not given"],
              ["Email", meta.email || "Not given"],
              ["Phone", meta.phone || "Not given"],
              ["City", meta.city || "Not given"],
              ["Timeline", meta.timeline || "Not given"],
              ["Deployment", TARGET_LABEL[target]],
            ] as Array<[string, string]>).map(([k, v]) => (
              <tr key={k}>
                <th>{k}</th>
                <td>{v}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      {meta.workloads.length > 0 && (
        <section className="qd-section">
          <h3 className="qd-h3">Intended workload</h3>
          <p className="qd-body">{meta.workloads.join(" · ")}</p>
        </section>
      )}

      {/* ------------------------------------------------------------ lines */}
      <section className="qd-section">
        <h3 className="qd-h3">
          Configuration, {lines.length} line{lines.length === 1 ? "" : "s"}, {totalUnits} unit
          {totalUnits === 1 ? "" : "s"}
        </h3>

        {lines.length === 0 ? (
          <p className="qd-body">No parts selected. Requirement described in the notes below.</p>
        ) : (
          <table className="qd-lines">
            <thead>
              <tr>
                <th style={{ width: "6%" }}>Qty</th>
                <th style={{ width: "20%" }}>Category</th>
                <th>Part</th>
                <th style={{ width: "20%" }}>Condition</th>
                <th style={{ width: "14%" }}>SKU</th>
              </tr>
            </thead>
            <tbody>
              {grouped.map((g) =>
                g.items.map((l, i) => (
                  <tr key={l.product.id}>
                    <td className="qd-num">{l.qty}</td>
                    <td>{i === 0 ? KIND_LABEL[g.kind] : ""}</td>
                    <td>
                      <strong>{l.product.brand}</strong> {l.product.model}
                    </td>
                    <td>{CONDITION_LABEL[l.product.condition]}</td>
                    <td className="qd-mono">{l.product.id}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        )}
      </section>

      {/* -------------------------------------------------------- telemetry */}
      {lines.length > 0 && (
        <section className="qd-section">
          <h3 className="qd-h3">Derived figures</h3>
          <table className="qd-kv qd-kv-2col">
            <tbody>
              {([
                ["Peak draw", `${summary.power.peakW.toLocaleString()} W`],
                ["Current at 230V", `${summary.power.amps230} A`],
                ["Heat rejected", `${summary.heatBtuHr.toLocaleString()} BTU/hr`],
                ["Rack space", summary.rackU ? `${summary.rackU}U` : "Tower, not rack mounted"],
                ["Processor cores", summary.cores ? String(summary.cores) : "n/a"],
                ["System memory", summary.memGb ? `${summary.memGb} GB` : "n/a"],
                ["Accelerator memory", summary.vramGb ? `${summary.vramGb} GB` : "n/a"],
                ["BF16 throughput", summary.bf16Tflops ? `${summary.bf16Tflops} TFLOPS` : "n/a"],
                ["Storage", summary.storageTb ? `${summary.storageTb} TB` : "n/a"],
              ] as Array<[string, string]>).map(([k, v]) => (
                <tr key={k}>
                  <th>{k}</th>
                  <td>{v}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <p className="qd-note">
            Figures are derived from published vendor specifications. Peak draw includes accelerator transient
            headroom, so it is higher than the sum of nameplate TDP.
          </p>
        </section>
      )}

      {/* ------------------------------------------------------- compat */}
      {findings.length > 0 && (
        <section className="qd-section qd-break">
          <h3 className="qd-h3">
            Compatibility report, {blocking.length} blocking, {warnings.length} warning
            {warnings.length === 1 ? "" : "s"}
          </h3>

          {blocking.length > 0 && (
            <>
              <h4 className="qd-h4">Blocking</h4>
              <ol className="qd-list">
                {blocking.map((f, i) => (
                  <li key={`b-${i}`}>
                    <strong>{f.title}.</strong> {f.detail}
                    {f.fix && <em> Suggested: {f.fix}</em>}
                  </li>
                ))}
              </ol>
            </>
          )}

          {warnings.length > 0 && (
            <>
              <h4 className="qd-h4">Warnings</h4>
              <ol className="qd-list">
                {warnings.map((f, i) => (
                  <li key={`w-${i}`}>
                    <strong>{f.title}.</strong> {f.detail}
                    {f.fix && <em> Suggested: {f.fix}</em>}
                  </li>
                ))}
              </ol>
            </>
          )}

          <p className="qd-note">
            Blocking findings mean the configuration will not assemble, boot or stay inside its electrical and
            thermal envelope as specified. We will propose corrections with the quotation.
          </p>
        </section>
      )}

      {/* ------------------------------------------------------------ notes */}
      {meta.notes.trim() && (
        <section className="qd-section">
          <h3 className="qd-h3">Requirements and site constraints</h3>
          <p className="qd-body qd-pre">{meta.notes}</p>
        </section>
      )}

      {/* ----------------------------------------------------------- footer */}
      <footer className="qd-foot">
        <p>
          This document records a request for quotation. It is not an order, an invoice or a price
          confirmation. {BRAND.name} will respond with availability, lead time and a landed quotation covering
          duty and taxes.
        </p>
        <p>
          {BRAND.legal} · {BRAND.cities.join(" · ")} · {BRAND.email} · {BRAND.phone}
        </p>
      </footer>
    </article>
  );
}
